"""Fail-closed promotion gate backed by hashed execution evidence.

``gate-results.json`` is generated by ``build_pipeline.py``. Hand-written
``PASS`` rows are invalid: every required gate must record its command, exit
code, hashed inputs, and hashed artifacts, all of which are rechecked here.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

from verification_core import sha256_file

COMMON_GATES = (
    "brief_pmid_preflight",
    "brief_claims_strict",
    "source_pmid_strict",
    "source_claims_strict",
    "source_retraction",
    "guideline_evidence",
    "guideline_evidence_crosscheck",
    "citation_zero_block",
    "cards_schema",
    "candidate_apkg_build",
    "package_note_count",
    "package_diacritics",
    "source_diacritics",
    "docx_build",
    "learner_smoke",
)
DISEASE_GATES = COMMON_GATES[:6] + ("depth_disease",) + COMMON_GATES[6:]
FOUNDATION_GATES = COMMON_GATES[:6] + ("depth_foundation",) + COMMON_GATES[6:]
PHARMACOLOGY_GATES = COMMON_GATES[:6] + ("depth_pharmacology",) + COMMON_GATES[6:]

# Every profile is executable only when its structural checker and test suite
# are reviewed. Exemptions never waive a required gate.
PROFILE_GATES = {
    "disease": DISEASE_GATES,
    "foundation": FOUNDATION_GATES,
    "pharmacology": PHARMACOLOGY_GATES,
}
KNOWN_GATES = frozenset(gate for gates in PROFILE_GATES.values() for gate in gates)

DEFAULT_DEPTH_CONTRACTS = {
    "foundation": {
        "min_total_words": 5000,
        "min_total_lines": 500,
        "min_sections": 10,
        "min_subsections": 12,
        "min_mechanism_chains": 3,
        "min_examples": 6,
        "min_misconceptions": 6,
        "min_checkpoints": 4,
        "min_cases_with_solutions": 2,
        "min_practical_tips": 10,
        "max_placeholder_count": 0,
        "no_padding": True,
    },
    "disease": {
        "min_total_words": 6000,
        "min_total_lines": 600,
        "min_sections": 10,
        "min_subsections": 14,
        "min_mechanism_chains": 4,
        "min_examples": 8,
        "min_misconceptions": 8,
        "min_checkpoints": 5,
        "min_cases_with_solutions": 3,
        "min_practical_tips": 12,
        "max_placeholder_count": 0,
        "no_padding": True,
    },
    "pharmacology": {
        "min_total_words": 6000,
        "min_total_lines": 600,
        "min_sections": 8,
        "min_subsections": 14,
        "min_mechanism_chains": 5,
        "min_examples": 8,
        "min_misconceptions": 8,
        "min_checkpoints": 5,
        "min_cases_with_solutions": 3,
        "min_practical_tips": 12,
        "max_placeholder_count": 0,
        "no_padding": True,
    },
}
CONTRACT_HEADING = re.compile(
    r"^##\s+0\.\s+Lesson profile & release contract\s*$", re.IGNORECASE | re.MULTILINE
)
JSON_FENCE = re.compile(r"^```json\s*\n(?P<payload>.*?)^```\s*$", re.DOTALL | re.MULTILINE)


class ContractError(ValueError):
    """Raised when the release contract or gate results cannot authorize promotion."""


def extract_contract(brief_text: str) -> dict[str, Any]:
    """Read exactly one JSON fence under the dedicated release-contract heading."""
    headings = list(CONTRACT_HEADING.finditer(brief_text))
    if not headings:
        raise ContractError("missing heading: ## 0. Lesson profile & release contract")
    if len(headings) != 1:
        raise ContractError("duplicate release-contract heading")
    heading = headings[0]
    section_start = heading.end()
    next_heading = re.search(
        r"^##\s+(?!0\.\s+Lesson profile & release contract\s*$)",
        brief_text[section_start:],
        re.MULTILINE | re.IGNORECASE,
    )
    section_end = section_start + next_heading.start() if next_heading else None
    section = brief_text[section_start:section_end]
    matches = list(JSON_FENCE.finditer(section))
    if not matches:
        raise ContractError("missing JSON contract block under release-contract heading")
    if len(matches) != 1:
        raise ContractError("duplicate JSON contract block under release-contract heading")
    match = matches[0]

    try:
        contract = json.loads(match.group("payload"))
    except json.JSONDecodeError as exc:
        raise ContractError(f"malformed contract JSON: {exc.msg}") from exc
    if not isinstance(contract, dict):
        raise ContractError("contract JSON must be an object")
    return contract


def _require_string_list(value: Any, field: str) -> list[str]:
    if not isinstance(value, list) or any(not isinstance(item, str) or not item for item in value):
        raise ContractError(f"{field} must be a list of non-empty strings")
    return value


def validate_contract(contract: dict[str, Any]) -> tuple[str, tuple[str, ...]]:
    """Validate profile policy. Exemptions never alter required gates."""
    expected_keys = {
        "profile",
        "mode",
        "required_gates",
        "lesson_depth_contract",
        "not_applicable",
        "approved_exemptions",
    }
    if set(contract) != expected_keys:
        raise ContractError(f"contract keys must be exactly: {sorted(expected_keys)}")

    mode = contract.get("mode")
    if mode != "L3_BEGINNER":
        raise ContractError(f"invalid contract mode: {mode!r}; mode must be 'L3_BEGINNER'")

    profile = contract["profile"]
    if profile not in PROFILE_GATES:
        raise ContractError(f"unknown profile: {profile!r}")

    required = _require_string_list(contract["required_gates"], "required_gates")
    if len(required) != len(set(required)):
        raise ContractError("required_gates contains duplicate gate")

    expected = PROFILE_GATES[profile]
    if set(required) != set(expected):
        missing = sorted(set(expected) - set(required))
        unknown = sorted(set(required) - set(expected))
        raise ContractError(f"required_gates must exactly match profile {profile}; missing={missing}, extra={unknown}")

    depth_contract = contract.get("lesson_depth_contract")
    if not isinstance(depth_contract, dict):
        raise ContractError("lesson_depth_contract must be a dict")

    expected_depth = DEFAULT_DEPTH_CONTRACTS[profile]
    diff_missing = set(expected_depth) - set(depth_contract)
    diff_extra = set(depth_contract) - set(expected_depth)
    if diff_missing or diff_extra:
        raise ContractError(
            f"lesson_depth_contract keys mismatch for profile '{profile}'; missing={sorted(diff_missing)}, extra={sorted(diff_extra)}"
        )
    for k, expected_val in expected_depth.items():
        actual_val = depth_contract.get(k)
        if actual_val != expected_val or type(actual_val) is not type(expected_val):
            raise ContractError(
                f"lesson_depth_contract.{k} must exactly match canonical default for profile '{profile}': {expected_val!r} (got {actual_val!r})"
            )
    not_applicable = _require_string_list(contract["not_applicable"], "not_applicable")
    if len(not_applicable) != len(set(not_applicable)):
        raise ContractError("not_applicable contains duplicate gate")
    unknown_na = sorted(set(not_applicable) - KNOWN_GATES)
    if unknown_na:
        raise ContractError(f"not_applicable contains unknown gate(s): {unknown_na}")
    overlap = sorted(set(not_applicable) & set(required))
    if overlap:
        raise ContractError(f"not_applicable cannot include required gate(s): {overlap}")

    exemptions = contract["approved_exemptions"]
    if not isinstance(exemptions, list):
        raise ContractError("approved_exemptions must be a list")
    for exemption in exemptions:
        if not isinstance(exemption, dict) or set(exemption) != {"gate", "reason", "approved_before_research"}:
            raise ContractError("each approved exemption needs exactly gate, reason, approved_before_research")
        if exemption["gate"] not in KNOWN_GATES or not isinstance(exemption["reason"], str) or not exemption["reason"].strip():
            raise ContractError("approved exemption has invalid gate or empty reason")
        if exemption["approved_before_research"] is not True:
            raise ContractError("approved exemption must state approved_before_research: true")
        if exemption["gate"] in required:
            raise ContractError(f"approved exemption cannot waive required gate: {exemption['gate']}")

    return profile, expected

def load_results(results_path: Path) -> list[dict[str, Any]]:
    try:
        results = json.loads(results_path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ContractError(f"cannot read results file: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise ContractError(f"malformed results JSON: {exc.msg}") from exc

    if not isinstance(results, list):
        raise ContractError("gate results must be a JSON list")
    required_keys = {"gate", "status", "command", "exit_code", "release_id", "inputs", "artifacts"}
    for result in results:
        if not isinstance(result, dict) or set(result) != required_keys:
            raise ContractError(f"each result must have exactly: {sorted(required_keys)}")
        if not isinstance(result["gate"], str) or not isinstance(result["status"], str):
            raise ContractError("result gate and status must be strings")
        if not isinstance(result["command"], list) or not result["command"] or not all(isinstance(v, str) and v for v in result["command"]):
            raise ContractError(f"{result['gate']}: command must be a non-empty string list")
        if not isinstance(result["exit_code"], int):
            raise ContractError(f"{result['gate']}: exit_code must be an integer")
        if not isinstance(result["release_id"], str) or not result["release_id"]:
            raise ContractError(f"{result['gate']}: release_id must be non-empty")
        for field in ("inputs", "artifacts"):
            rows = result[field]
            if not isinstance(rows, list) or not rows:
                raise ContractError(f"{result['gate']}: {field} must be non-empty")
            for row in rows:
                if not isinstance(row, dict) or set(row) != {"path", "sha256"}:
                    raise ContractError(f"{result['gate']}: malformed {field} evidence")
                if not isinstance(row["path"], str) or not re.fullmatch(r"[0-9a-f]{64}", row.get("sha256", "")):
                    raise ContractError(f"{result['gate']}: invalid {field} path/hash")
    return results


def _validate_hashed_paths(result: dict[str, Any], field: str) -> None:
    for evidence in result[field]:
        path = Path(evidence["path"])
        if not path.is_file():
            raise ContractError(f"{result['gate']}: missing {field} file: {path}")
        actual = sha256_file(path)
        if actual != evidence["sha256"]:
            raise ContractError(f"{result['gate']}: stale or modified {field} file: {path}")


def validate_results(results: list[dict[str, Any]], required: tuple[str, ...]) -> None:
    gates = [result["gate"] for result in results]
    duplicates = sorted({gate for gate in gates if gates.count(gate) > 1})
    if duplicates:
        raise ContractError(f"duplicate result gate(s): {duplicates}")

    unknown = sorted(set(gates) - set(required))
    if unknown:
        raise ContractError(f"unknown or non-required result gate(s): {unknown}")
    missing = sorted(set(required) - set(gates))
    if missing:
        raise ContractError(f"missing required result gate(s): {missing}")

    release_ids = {result["release_id"] for result in results}
    if len(release_ids) != 1:
        raise ContractError(f"all gates must share one release_id, got: {sorted(release_ids)}")
    for result in results:
        if result["status"] != "PASS" or result["exit_code"] != 0:
            raise ContractError(f"required gate must be PASS with exit_code 0: {result['gate']}={result['status']}/{result['exit_code']}")
        _validate_hashed_paths(result, "inputs")
        _validate_hashed_paths(result, "artifacts")


def main() -> int:
    parser = argparse.ArgumentParser(description="Fail-closed promotion gate for medical lesson candidates")
    parser.add_argument("brief", nargs="?", help="Research Brief containing the locked release contract")
    parser.add_argument("--results", help="Evidence manifest generated by build_pipeline.py")
    parser.add_argument("--list-profiles", action="store_true", help="Print supported profiles and required gates")
    args = parser.parse_args()

    if args.list_profiles:
        print(json.dumps(PROFILE_GATES, ensure_ascii=False, indent=2))
        return 0
    if not args.brief or not args.results:
        parser.error("brief and --results are required unless --list-profiles is used")

    try:
        contract = extract_contract(Path(args.brief).read_text(encoding="utf-8"))
        profile, required = validate_contract(contract)
        validate_results(load_results(Path(args.results)), required)
    except (OSError, ContractError) as exc:
        print(f"PUBLISH BLOCKED: {exc}", file=sys.stderr)
        return 1

    print(f"PUBLISH READY: profile={profile}; {len(required)} required gates have valid hashed evidence")
    return 0


if __name__ == "__main__":
    sys.exit(main())
