# -*- coding: utf-8 -*-
"""PED-07 MASTER deck cards data: Co giật do sốt & Cắt cơn co giật / Trạng thái động kinh.
100% BASIC type, chuẩn Hierarchical Scaffolding, Back-Purity 100%, 0 LaTeX.
Section codes S0-S9 (RELEASE lesson).
Coverage gate requires >=1 card per section.
"""

cards_data = [
    {
        "id": "PED07-S01",
        "track": "barem_goc",
        "type": "basic",
        "category": "Khung tổng quan bài học",
        "section": "S0",
        "front": "Khung 6 mục tiêu học tập chuyên sâu của bài Co giật do sốt & Trạng thái động kinh (PED-07) gồm những gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Phân loại chuẩn xác trên lâm sàng: Co giật do sốt đơn thuần (Simple FS), Co giật do sốt phức hợp (Complex FS) và Trạng thái động kinh do sốt (FSE).<br>2) Nắm vững chỉ định cận lâm sàng dựa trên chứng cứ theo AAP 2011: Hạn chế tối đa chọc dò tủy sống thường quy, điện não đồ (EEG) và chụp CT/MRI sọ não khi không có dấu hiệu cờ đỏ.<br>3) Làm chủ thuật toán cấp cứu trạng thái động kinh theo Hội Động kinh Hoa Kỳ (AES 2016) theo từng mốc thời gian T1 (5 phút) và T2 (30 phút).<br>4) Sử dụng thành thạo và chính xác liều lượng các thuốc chống co giật Bước 1 (Midazolam, Lorazepam, Diazepam) và Bước 2 (Levetiracetam, Fosphenytoin, Valproate).<br>5) Phân tích thấu đáo kết quả từ các thử nghiệm lâm sàng đối chứng ngẫu nhiên lớn: RAMPART, ESETT, ConSEPT, EcLiPSE và nghiên cứu FEBSTAT.<br>6) Tham vấn khoa học, an toàn cho phụ huynh: Không dùng thuốc chống động kinh dự phòng thường quy theo AAP 2008 và xử trí hạ sốt đúng cách.<br><br><b>💡 Giải thích của AI:</b><br>Sáu mục tiêu này bao quát toàn diện năng lực cấp cứu thần kinh nhi khoa: từ phân loại chẩn đoán ban đầu đến xử trí cấp cứu từng phút và tư vấn dài hạn cho gia đình.",
        "extra": "📖 Nguồn: Bài học PED-07 (Mục 0.2 Mục tiêu học tập chuyên sâu)",
        "tags": ["PED-07", "Barem-goc", "Tong-quan", "Muc-tieu"],
    },
    {
        "id": "PED07-S02",
        "track": "barem_goc",
        "type": "basic",
        "category": "Dịch tễ học co giật do sốt",
        "section": "S0",
        "front": "Tỷ lệ mắc và lứa tuổi có đỉnh mắc bệnh cao nhất của co giật do sốt ở trẻ em là bao nhiêu?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Tỷ lệ mắc chung: Chiếm từ 2% đến 5% trẻ em trong độ tuổi từ 6 đến 60 tháng tuổi.<br>2) Đỉnh tuổi mắc bệnh cao nhất: Từ 12 đến 18 tháng tuổi.<br>3) Tỷ lệ giới tính: Bé trai có tỷ lệ mắc hơi cao hơn bé gái (tỷ lệ khoảng 1,1 : 1 đến 1,2 : 1).<br><br><b>💡 Giải thích của AI:</b><br>Đây là dạng rối loạn co giật phổ biến nhất ở lứa tuổi nhi khoa. Lứa tuổi 12–18 tháng là giai đoạn hệ thần kinh phát triển bùng nổ nhưng cơ chế ức chế GABA chưa hoàn thiện, kết hợp với tần suất nhiễm siêu vi đường hô hấp cao.",
        "extra": "📖 Nguồn: AAP Clinical Practice Guideline on Febrile Seizures & Nelson Pediatrics",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Dich-te-co-giat"],
    },
    {
        "id": "PED07-S03",
        "track": "barem_goc",
        "type": "basic",
        "category": "Mục tiêu cấp cứu ban đầu",
        "section": "S0",
        "front": "Mục tiêu cấp cứu tối thượng của người thầy thuốc khi tiếp cận trẻ đang trong cơn co giật là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Ưu tiên số 1: Đảm bảo thông khí, cung cấp oxy, kiểm soát đường thở và duy trì huyết động ổn định (tiếp cận ABC).<br>2) Ưu tiên số 2: Cắt cơn co giật nhanh chóng bằng thuốc thích hợp trước khi cơn kéo dài quá 5 phút (mốc T1).<br>3) Nguyên tắc an toàn: Tuyệt đối không hoảng loạn, không nhét bất kỳ vật cứng nào vào miệng trẻ và đặt trẻ nằm nghiêng an toàn.<br><br><b>💡 Giải thích của AI:</b><br>Tử vong và tổn thương não trong co giật thường không phải do bản thân dòng điện co giật gây ra trực tiếp trong vài phút đầu, mà do suy hô hấp thiếu oxy mô, hít sặc đờm dãi hoặc tụt huyết áp kéo dài.",
        "extra": "📖 Nguồn: PALS & AES 2016 Status Epilepticus Guidelines",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Muc-tieu-cap-cuu"],
    },
    {
        "id": "PED07-S04",
        "track": "barem_goc",
        "type": "basic",
        "category": "Cơ chế khởi phát do sốt",
        "section": "S0",
        "front": "Tại sao nhiệt độ cơ thể tăng cao đột ngột lại có thể kích hoạt cơn co giật ở trẻ nhỏ?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Tăng tốc độ khử cực: Nhiệt độ tăng cao làm gia tăng tốc độ đóng mở của các kênh ion phụ thuộc điện thế trên màng tế bào thần kinh, rút ngắn thời gian trơ.<br>2) Kích hoạt các kênh ion nhạy cảm nhiệt độ (như kênh TRPV4).<br>3) Thở nhanh do sốt gây kiềm hô hấp nhẹ: Làm giảm nồng độ Canxi ion hóa trong máu và dịch não tủy, trực tiếp hạ thấp ngưỡng kích thích điện học của vỏ não.<br><br><b>💡 Giải thích của AI:</b><br>Tốc độ tăng nhiệt độ đột ngột trong giai đoạn đầu của đợt sốt là yếu tố kích phát mạnh nhất, giải thích vì sao nhiều trẻ vừa sốt 30 phút là đã xuất hiện cơn giật ngay tại nhà.",
        "extra": "📖 Nguồn: Bài học PED-07 (Mục 0.1 Nền tảng sinh lý bệnh)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Co-che-sot-gay-giat"],
    },
    {
        "id": "PED07-S05",
        "track": "barem_goc",
        "type": "basic",
        "category": "Định nghĩa chuẩn AAP",
        "section": "S1",
        "front": "Định nghĩa co giật do sốt (Febrile Seizures) theo Viện Hàn lâm Nhi khoa Hoa Kỳ (AAP) quy định độ tuổi, thân nhiệt và 3 điều kiện loại trừ nào?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>Co giật do sốt là biến cố co giật xảy ra ở trẻ em:<br>1) Độ tuổi: Từ 6 đến 60 tháng tuổi (hoặc 3 tháng đến 5 tuổi).<br>2) Thân nhiệt: Có kèm theo sốt (thân nhiệt đo ở nách hoặc hậu môn ≥ 38,0°C).<br>3) Ba điều kiện loại trừ bắt buộc:<br>- Không có bằng chứng nhiễm trùng hệ thần kinh trung ương (viêm màng não, viêm não, áp xe não).<br>- Không có rối loạn điện giải cấp tính nghiêm trọng hoặc rối loạn chuyển hóa toàn thân (hạ đường huyết, hạ calci, hạ natri máu).<br>- Trẻ không có tiền sử co giật không do sốt trước đó và không mắc bệnh lý thần kinh tiến triển mạn tính.<br><br><b>💡 Giải thích của AI:</b><br>Định nghĩa này phân tách rõ ràng giữa một phản ứng sinh lý thần kinh lành tính liên quan đến sốt với các bệnh lý nhiễm trùng ngoại khoa hoặc bệnh động kinh thực thể.",
        "extra": "📖 Nguồn: AAP Clinical Practice Guideline (Pediatrics 2011, PMID: 21285335)",
        "tags": ["PED-07", "Barem-goc", "Tong-quan", "Dinh-nghia-AAP"],
    },
    {
        "id": "PED07-S06",
        "track": "barem_goc",
        "type": "basic",
        "category": "Khung bảng đối chiếu 3 thể",
        "section": "S1",
        "front": "Khung bảng đối chiếu phân loại 3 thể co giật do sốt: Đơn thuần (Simple FS) vs Phức hợp (Complex FS) vs Trạng thái động kinh do sốt (FSE)?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Co giật do sốt ĐƠN THUẦN (70–75%): Cơn toàn thể đối xứng; thời gian &lt; 15 phút (thường &lt; 5 phút); chỉ có duy nhất 1 cơn trong 24 giờ; không có dấu thần kinh khu trú sau cơn.<br>2) Co giật do sốt PHỨC HỢP (20–25%): Có ít nhất 1 trong 3 dấu hiệu: Cơn giật cục bộ khu trú; HOẶC cơn kéo dài ≥ 15 phút; HOẶC tái phát ≥ 2 cơn trong vòng 24 giờ (hoặc trong 1 đợt sốt); có thể kèm liệt Todd sau cơn.<br>3) TRẠNG THÁI ĐỘNG KINH DO SỐT - FSE (khoảng 5%): Cơn co giật kéo dài liên tục hoặc nhiều cơn ngắt quãng mà trẻ không hồi phục hoàn toàn tri giác kéo dài ≥ 30 phút.<br><br><b>💡 Giải thích của AI:</b><br>Phân loại đúng 3 thể này là bước rẽ nhánh quyết định: thể đơn thuần không cần xét nghiệm cận lâm sàng xâm lấn; thể phức tạp cần tầm soát cẩn trọng; thể FSE là cấp cứu tối khẩn.",
        "extra": "📖 Nguồn: Bài học PED-07 (Bảng 1.2 Phân loại lâm sàng)",
        "tags": ["PED-07", "Barem-goc", "Tong-quan", "Bang-doi-chieu-3-the"],
    },
    {
        "id": "PED07-S07",
        "track": "barem_goc",
        "type": "basic",
        "category": "Đặc điểm co giật do sốt đơn thuần",
        "section": "S1",
        "front": "Ba tiêu chuẩn kinh điển của Co giật do sốt đơn thuần (Simple Febrile Seizures) là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Tính chất cơn: Co cứng - co giật toàn thể, đối xứng hai bên cơ thể.<br>2) Thời gian cơn: Ngắn, kéo dài &lt; 15 phút (đại đa số tự ngừng trong vòng &lt; 5 phút).<br>3) Tần số xuất hiện: Chỉ xảy ra DUY NHẤT 1 CƠN trong vòng 24 giờ hoặc trong cùng một đợt sốt.<br>Kèm theo: Giai đoạn sau cơn ngắn, trẻ tỉnh táo hoàn toàn, không có liệt thần kinh khu trú.<br><br><b>💡 Giải thích của AI:</b><br>Thể đơn thuần chiếm tới gần 3/4 tổng số các ca co giật do sốt. Tiên lượng của thể này hoàn toàn lành tính, không gây suy giảm trí tuệ và không làm tăng nguy cơ tử vong.",
        "extra": "📖 Nguồn: AAP 2011 Guideline & Nelson Textbook of Pediatrics",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Co-giat-don-thuan"],
    },
    {
        "id": "PED07-S08",
        "track": "barem_goc",
        "type": "basic",
        "category": "Đặc điểm co giật do sốt phức hợp",
        "section": "S1",
        "front": "Ba tiêu chuẩn chẩn đoán Co giật do sốt phức hợp (Complex Febrile Seizures) theo AAP là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>Chẩn đoán khi có ÍT NHẤT 1 TRONG 3 TIÊU CHUẨN sau:<br>1) Tính chất cơn mang tính chất CỤC BỘ (khởi phát lệch một bên mắt, méo miệng, giật giật một bên tay/chân).<br>2) Thời gian cơn kéo dài KÉO DÀI ≥ 15 PHÚT.<br>3) TÁI PHÁT ≥ 2 CƠN trong vòng 24 giờ (hoặc nhiều hơn 1 cơn trong cùng một đợt sốt).<br><br><b>💡 Giải thích của AI:</b><br>Chỉ cần thỏa mãn 1 trong 3 yếu tố trên là xếp vào thể phức hợp. Thể này có nguy cơ cao hơn liên quan đến tổn thương cấu trúc não, nhiễm trùng thần kinh hoặc tiến triển thành động kinh sau này.",
        "extra": "📖 Nguồn: AAP 2011 Guideline (Pediatrics 2011, PMID: 21285335)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Co-giat-phuc-hop"],
    },
    {
        "id": "PED07-S09",
        "track": "barem_goc",
        "type": "basic",
        "category": "Trạng thái động kinh do sốt",
        "section": "S1",
        "front": "Định nghĩa và ý nghĩa lâm sàng của Trạng thái động kinh do sốt (Febrile Status Epilepticus - FSE)?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Định nghĩa: Cơn co giật do sốt kéo dài liên tục từ ≥ 30 phút HOẶC chuỗi các cơn co giật liên tiếp mà trẻ không hồi phục hoàn toàn tri giác giữa các cơn kéo dài ≥ 30 phút.<br>2) Tỷ lệ mắc: Chiếm khoảng 5% tổng số các ca co giật do sốt, nhưng chiếm tới một phần ba các ca trạng thái động kinh ở trẻ nhũ nhi.<br>3) Ý nghĩa lâm sàng: Là một cấp cứu thần kinh tối khẩn, nguy cơ cao gây tổn thương hồi hải mã và phù não cấp nếu không cắt cơn kịp thời.<br><br><b>💡 Giải thích của AI:</b><br>Nghiên cứu FEBSTAT chỉ ra FSE là nguyên nhân hàng đầu dẫn đến xơ hóa thùy thái dương và động kinh kháng trị sau này.",
        "extra": "📖 Nguồn: FEBSTAT Study (Epilepsia 2012, PMID: 22841663)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "FSE-dinh-nghia"],
    },
    {
        "id": "PED07-S10",
        "track": "barem_goc",
        "type": "basic",
        "category": "Liệt Todd sau cơn",
        "section": "S1",
        "front": "Hiện tượng Liệt Todd (Todd's Paresis) sau cơn co giật là gì và có ý nghĩa lâm sàng như thế nào?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Định nghĩa: Tình trạng yếu hoặc liệt vận động cục bộ một chi hoặc nửa người thoáng qua xuất hiện ngay sau khi cơn co giật kết thúc.<br>2) Thời gian diễn tiến: Thường hồi phục hoàn toàn trong vòng vài phút đến 24–48 giờ.<br>3) Ý nghĩa lâm sàng: Là bằng chứng khẳng định cơn giật có tính chất cục bộ (co giật phức hợp), chỉ điểm vùng vỏ não vận động đối bên bị ức chế sau phóng điện kịch phát.<br><br><b>💡 Giải thích của AI:</b><br>Khi thấy liệt Todd, bác sĩ phải theo dõi sát sự phục hồi vận động và chỉ định chụp MRI sọ não để loại trừ các tổn thương cấu trúc não (u não, loạn sản vỏ, dị dạng mạch máu).",
        "extra": "📖 Nguồn: Nelson Textbook of Pediatrics 21st (Chương Seizure Disorders)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Liet-Todd"],
    },
    {
        "id": "PED07-S11",
        "track": "barem_goc",
        "type": "basic",
        "category": "Hội chứng Dravet",
        "section": "S1",
        "front": "Đặc điểm di truyền, lâm sàng và chống chỉ định thuốc sống còn trong Hội chứng Dravet là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Di truyền: Khoảng 80% trường hợp mang đột biến mất chức năng gen SCN1A mã hóa kênh Natri NaV1.1.<br>2) Lâm sàng: Khởi phát rất sớm (&lt; 12 tháng tuổi), cơn co giật do sốt kéo dài, có tính chất co giật nửa người luân chuyển bên (lúc bên trái lúc bên phải), tái phát liên tục và kháng thuốc.<br>3) CHỐNG CHỈ ĐỊNH SỐNG CÒN: Tuyệt đối cấm dùng các thuốc chẹn kênh Natri (Carbamazepine, Oxcarbazepine, Phenytoin, Lamotrigine) vì sẽ làm nặng thêm tình trạng co giật và đẩy trẻ vào trạng thái động kinh tử vong.<br><br><b>💡 Giải thích của AI:</b><br>Kênh NaV1.1 nằm chủ yếu trên các tế bào thần kinh ức chế GABA. Đột biến làm suy yếu sẵn hệ ức chế, nếu dùng thêm thuốc chẹn kênh Natri sẽ triệt tiêu hoàn toàn khả năng ức chế của não, gây phóng điện bùng nổ.",
        "extra": "📖 Nguồn: Dravet Syndrome Clinical Practice Guidelines & Epilepsia",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Hoi-chung-Dravet"],
    },
    {
        "id": "PED07-S12",
        "track": "barem_goc",
        "type": "basic",
        "category": "Hội chứng GEFS+ và FIRES",
        "section": "S1",
        "front": "Khái niệm và đặc điểm cốt lõi của Hội chứng GEFS+ và Hội chứng FIRES liên quan đến sốt ở trẻ em?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Hội chứng GEFS+ (Genetic Epilepsy with Febrile Seizures Plus): Bệnh lý di truyền trội trên NST thường; các thành viên trong gia đình tiếp tục xuất hiện co giật do sốt kéo dài sau 6 tuổi và có thể kèm các thể động kinh toàn thể khác.<br>2) Hội chứng FIRES (Febrile Infection-Related Epilepsy Syndrome): Trạng thái động kinh bùng phát dữ dội sau một đợt nhiễm trùng sốt thông thường ở trẻ em khỏe mạnh trước đó; đáp ứng rất kém với thuốc chống động kinh quy ước, đòi hỏi liệu pháp miễn dịch (IVIG, Steroid, Anakinra) và chế độ ăn sinh ceton.<br><br><b>💡 Giải thích của AI:</b><br>Nhận diện sớm các hội chứng đặc biệt này giúp tránh việc dùng sai thuốc và định hướng can thiệp miễn dịch hoặc chế độ ăn kịp thời.",
        "extra": "📖 Nguồn: ILAE Classification & Guidelines on Febrile Seizure Syndromes",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "GEFS-va-FIRES"],
    },
    {
        "id": "PED07-S13",
        "track": "barem_goc",
        "type": "basic",
        "category": "Não bộ chưa trưởng thành",
        "section": "S2",
        "front": "Đặc điểm sinh lý thần kinh của não bộ trẻ nhỏ (6–60 tháng) khiến trẻ có tính kích thích nội tại cao và dễ bị co giật?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Hệ thống kích thích phát triển sớm: Các thụ thể dẫn truyền kích thích NMDA và AMPA sử dụng Glutamate phát triển mạnh với mật độ dày đặc.<br>2) Hệ thống ức chế chưa hoàn thiện: Thụ thể ức chế GABA-A chưa phát triển đầy đủ cả về số lượng lẫn cấu trúc tiểu đơn vị.<br>3) Bơm Clorua KCC2 biểu hiện thấp: Khiến nồng độ Cl⁻ nội bào cao hơn người lớn, làm cho tác dụng kích hoạt thụ thể GABA đôi khi còn gây khử cực kích thích thay vì tăng phân cực ức chế.<br><br><b>💡 Giải thích của AI:</b><br>Sự mất cân bằng bẩm sinh giữa 'chân ga kích thích quá mạnh' và 'chân phanh ức chế quá yếu' tạo nên mảnh đất màu mỡ cho cơn co giật bùng nổ khi gặp tác nhân kích phát như sốt cao.",
        "extra": "📖 Nguồn: Bài học PED-07 (Mục 2.1 Sinh lý bệnh học não chưa trưởng thành)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Nao-chua-truong-thanh"],
    },
    {
        "id": "PED07-S14",
        "track": "barem_goc",
        "type": "basic",
        "category": "Cytokine trong sốt co giật",
        "section": "S2",
        "front": "Vai trò của các cytokine tiền viêm (IL-1β, TNF-α) trong cơ chế khởi phát co giật do sốt là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Phản ứng viêm toàn thân kích hoạt giải phóng các cytokine gây sốt: Interleukin-1 beta (IL-1β), Tumor Necrosis Factor-alpha (TNF-α) và IL-6.<br>2) IL-1β gắn trực tiếp vào thụ thể IL-1R1 trên tế bào thần kinh, làm tăng tính thấm hàng rào máu não.<br>3) Kích hoạt dòng Canxi và Natri đi vào tế bào qua kênh thụ thể NMDA, thúc đẩy phóng điện kịch phát đồng bộ của các nơ ron vỏ não.<br><br><b>💡 Giải thích của AI:</b><br>Cytokine không chỉ là chất gây sốt tại vùng dưới đồi mà còn đóng vai trò như một chất điều biến thần kinh trực tiếp hạ thấp ngưỡng co giật.",
        "extra": "📖 Nguồn: Neurobiology of Febrile Seizures & Cytokine Networks",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Cytokine-IL1-TNF"],
    },
    {
        "id": "PED07-S15",
        "track": "barem_goc",
        "type": "basic",
        "category": "Kiềm hô hấp hạ Ca ion hóa",
        "section": "S2",
        "front": "Cơ chế kiềm hô hấp do sốt gây hạ Canxi ion hóa máu và hạ ngưỡng co giật ở trẻ em diễn ra như thế nào?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Trẻ sốt cao thường thở rất nhanh ➜ Gây đào thải quá mức CO₂ dẫn đến KIỀM HÔ HẤP cấp tính.<br>2) pH máu tăng làm các ion H⁺ tách khỏi Albumin, giải phóng các vị trí mang điện tích âm.<br>3) Ion Canxi tự do (Ca²⁺ ion hóa) bị hút gắn chặt vào Albumin ➜ Nồng độ Canxi ion hóa trong máu và dịch não tủy sụt giảm cấp tính.<br>4) Hậu quả: Màng tế bào thần kinh bị mất ổn định điện thế, ngưỡng kích thích tụt dốc, kích hoạt cơn co giật bùng phát.<br><br><b>💡 Giải thích của AI:</b><br>Chuỗi cơ chế: [Sốt] ➜ [Thở nhanh] ➜ [Kiềm hô hấp] ➜ [Hạ Ca²⁺ ion hóa] ➜ [Kích hoạt NMDA] ➜ [Co giật bùng nổ].",
        "extra": "📖 Nguồn: Bài học PED-07 (Mục 2.1 Chuỗi cơ chế hạ ngưỡng kích thích)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Kiem-ho-hap-ha-Ca"],
    },
    {
        "id": "PED07-S16",
        "track": "barem_goc",
        "type": "basic",
        "category": "Khung 5 tầng tổn thương não",
        "section": "S2",
        "front": "Khung 5 tầng tổn thương tế bào não lũy tiến khi cơn co giật kéo dài liên tục trên 30 phút gồm những gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Tầng 1: Tăng kích thích tế bào thần kinh và suy kiệt năng lượng (cạn kiệt ATP và Glucose não).<br>2) Tầng 2: Độc tính kích thích ngoại bào do tích tụ Glutamate (Excitotoxicity).<br>3) Tầng 3: Quá tải Canxi nội bào và rối loạn chức năng ty thể (kích hoạt Calpain và Caspase-3).<br>4) Tầng 4: Phù nề tế bào độc tế bào (Cytotoxic edema) và hoại tử tế bào thần kinh chọn lọc tại hồi hải mã CA1.<br>5) Tầng 5: Tái tổ chức synap bất thường (mọc chồi sợi rêu) và sinh bệnh động kinh dài hạn.<br><br><b>💡 Giải thích của AI:</b><br>Năm tầng tổn thương này giải thích vì sao mốc 30 phút (T2) được coi là 'ranh giới sinh tử': vượt qua mốc này, tổn thương nơ ron không hồi phục bắt đầu diễn ra.",
        "extra": "📖 Nguồn: Bài học PED-07 (Mục 2.2 Chuỗi 5 tầng tổn thương tế bào)",
        "tags": ["PED-07", "Barem-goc", "Tong-quan", "5-tang-ton-thuong-nao"],
    },
    {
        "id": "PED07-S17",
        "track": "barem_goc",
        "type": "basic",
        "category": "Chi tiết Tầng 1 & 2 tổn thương não",
        "section": "S2",
        "front": "Cơ chế suy kiệt năng lượng (Tầng 1) và độc tính Glutamate (Tầng 2) trong co giật kéo dài diễn ra như thế nào?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Tầng 1 (Suy kiệt năng lượng): Cơn phóng điện liên tục buộc bơm Na⁺/K⁺-ATPase phải hoạt động hết công suất để tái lập điện thế màng ➜ Tiêu thụ cạn kiệt lượng Glucose và ATP dự trữ trong nhu mô não.<br>2) Tầng 2 (Độc tính Glutamate): Các tế bào thần kinh đệm bị cạn kiệt năng lượng không thể tái hấp thu Glutamate từ khe synap ➜ Glutamate tồn đọng nồng độ cao kích hoạt liên tục thụ thể NMDA, mở toang cửa cho ion Ca²⁺ và Na⁺ tràn vào tế bào.<br><br><b>💡 Giải thích của AI:</b><br>Sự tích tụ Glutamate chính là nguồn cơn biến một biến cố điện học đơn thuần thành một phản ứng độc học tế bào phá hủy cấu trúc não.",
        "extra": "📖 Nguồn: Bài học PED-07 (Mục 2.2 Tầng 1 & 2)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Tang-1-2-Glutamate"],
    },
    {
        "id": "PED07-S18",
        "track": "barem_goc",
        "type": "basic",
        "category": "Chi tiết Tầng 3 & 4 tổn thương não",
        "section": "S2",
        "front": "Cơ chế quá tải Canxi (Tầng 3) và tổn thương hoại tử hồi hải mã CA1 (Tầng 4) trong trạng thái động kinh kéo dài?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Tầng 3 (Quá tải Canxi): Nồng độ Ca²⁺ nội bào tăng vọt kích hoạt các enzyme tiêu hủy protein (Calpain, Caspase-3, Phospholipase A2) ➜ Phá hủy màng ty thể và giải phóng Cytochrome C kích hoạt chu trình chết tế bào.<br>2) Tầng 4 (Hoại tử chọn lọc hồi hải mã CA1): Vùng tế bào tháp CA1 của hồi hải mã có mật độ thụ thể NMDA cao nhất nên là vùng nhạy cảm nhất ➜ Bị phù tế bào nhiễm độc, thoái hóa và chết tế bào hàng loạt.<br><br><b>💡 Giải thích của AI:</b><br>Tổn thương chọn lọc vùng CA1 hồi hải mã là nền tảng giải phẫu bệnh học của hội chứng xơ teo thùy thái dương ở bệnh nhân động kinh sau này.",
        "extra": "📖 Nguồn: Bài học PED-07 (Mục 2.2 Tầng 3 & 4) & FEBSTAT Study",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Tang-3-4-Hai-ma-CA1"],
    },
    {
        "id": "PED07-S19",
        "track": "barem_goc",
        "type": "basic",
        "category": "Chi tiết Tầng 5 mọc chồi sợi rêu",
        "section": "S2",
        "front": "Hiện tượng Mọc chồi sợi rêu (Mossy Fiber Sprouting - Tầng 5) sau trạng thái động kinh kéo dài dẫn đến bệnh động kinh như thế nào?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Sau khi các tế bào thần kinh vùng hồi hải mã bị chết, các sợi trục của tế bào hạt hồi răng mọc chồi bất thường để tìm kiếm synap mới.<br>2) Các sợi chồi này tạo synap tự kích thích quay trở lại chính tế bào hạt (Recurrent excitatory circuits).<br>3) Hậu quả: Tạo nên các vòng hồi tiếp tự kích thích vĩnh viễn trong vỏ não ➜ Hình thành ổ động kinh mạn tính (Epileptogenesis), dẫn đến bệnh Động kinh thùy thái dương kháng trị.<br><br><b>💡 Giải thích của AI:</b><br>Đây là bằng chứng phân tử giải thích vì sao trạng thái động kinh kéo dài không chỉ nguy hiểm trong lúc cấp cứu mà còn để lại di chứng động kinh suốt đời.",
        "extra": "📖 Nguồn: Bài học PED-07 (Mục 2.2 Tầng 5)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Moc-choi-soi-reu"],
    },
    {
        "id": "PED07-S20",
        "track": "barem_goc",
        "type": "basic",
        "category": "Vì sao co giật dưới 5 phút lành tính",
        "section": "S2",
        "front": "Tại sao các cơn co giật do sốt tự ngừng trong vòng dưới 5 phút lại hoàn toàn lành tính và không để lại tổn thương não?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Dưới 5 phút, lưu lượng máu não và nồng độ oxy/glucose vận chuyển tới mô não tăng vọt bù trừ đủ để đáp ứng nhu cầu năng lượng của tế bào.<br>2) Cơ chế bơm tái hấp thu Glutamate tại khe synap chưa bị suy sụp.<br>3) Hệ thống đệm Canxi nội bào chưa bị quá tải, chưa kích hoạt chu trình chết tế bào theo chương trình.<br>➜ Tế bào não hồi phục hoàn toàn bình thường ngay sau khi cơn giật dứt.<br><br><b>💡 Giải thích của AI:</b><br>Hiểu được cơ chế này giúp người thầy thuốc vững tâm giải thích và trấn an phụ huynh rằng cơn co giật đơn thuần ngắn không làm 'cháy não' hay làm trẻ chậm phát triển trí tuệ.",
        "extra": "📖 Nguồn: AAP Clinical Practice Guideline on Febrile Seizures 2008 & 2011",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Co-giat-duoi-5-phut"],
    },
    {
        "id": "PED07-S21",
        "track": "barem_goc",
        "type": "basic",
        "category": "Khung cận lâm sàng AAP 2011",
        "section": "S3",
        "front": "Khung nguyên tắc chỉ định xét nghiệm cận lâm sàng ở trẻ co giật do sốt theo Guideline AAP 2011 quy định như thế nào?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Xét nghiệm máu thường quy (công thức máu, điện giải đồ, đường huyết): KHÔNG KHUYẾN CÁO THƯỜNG QUY cho trẻ co giật do sốt đơn thuần tỉnh táo tốt.<br>2) Điện não đồ (EEG): CHỐNG CHỈ ĐỊNH / KHÔNG LÀM THƯỜNG QUY trong đánh giá ban đầu trẻ co giật đơn thuần.<br>3) Chụp CT/MRI sọ não: KHÔNG LÀM THƯỜNG QUY cho trẻ co giật do sốt đơn thuần.<br>4) Chọc dò dịch não tủy (LP): Chỉ định có chọn lọc dựa trên dấu hiệu gợi ý viêm màng não.<br><br><b>💡 Giải thích của AI:</b><br>AAP 2011 thực hiện chiến lược giảm thiểu can thiệp xâm lấn và lãng phí y tế: ở trẻ co giật do sốt đơn thuần đã tỉnh táo, việc tìm kiếm ổ nhiễm trùng thông thường (viêm tai giữa, viêm họng, nhiễm siêu vi) quan trọng hơn làm xét nghiệm thần kinh.",
        "extra": "📖 Nguồn: AAP Clinical Practice Guideline (Pediatrics 2011, PMID: 21285335)",
        "tags": ["PED-07", "Barem-goc", "Tong-quan", "Can-lam-sang-AAP-2011"],
    },
    {
        "id": "PED07-S22",
        "track": "barem_goc",
        "type": "basic",
        "category": "Vì sao không làm EEG thường quy",
        "section": "S3",
        "front": "Tại sao Viện Hàn lâm Nhi khoa Hoa Kỳ (AAP 2011) khuyến cáo không ghi điện não đồ (EEG) thường quy ở trẻ co giật do sốt đơn thuần?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) EEG ghi trong giai đoạn sốt thường có sóng chậm lan tỏa không đặc hiệu (do sốt và sau cơn), dễ gây chẩn đoán quá mức (Dương tính giả).<br>2) Kết quả EEG hoàn toàn KHÔNG DỰ ĐOÁN ĐƯỢC nguy cơ tái phát co giật do sốt trong tương lai.<br>3) EEG cũng KHÔNG DỰ ĐOÁN ĐƯỢC nguy cơ phát triển thành bệnh động kinh sau này.<br><br><b>💡 Giải thích của AI:</b><br>Làm EEG chỉ gây thêm lo lắng hoang mang cho cha mẹ và có thể dẫn đến việc chỉ định dùng thuốc chống động kinh không cần thiết cho một đứa trẻ hoàn toàn lành tính.",
        "extra": "📖 Nguồn: AAP 2011 Guideline (Pediatrics 2011, PMID: 21285335)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Cam-EEG-thuong-quy"],
    },
    {
        "id": "PED07-S23",
        "track": "barem_goc",
        "type": "basic",
        "category": "Vì sao không chụp CT/MRI thường quy",
        "section": "S3",
        "front": "Tại sao không khuyến cáo chụp CT hoặc MRI sọ não thường quy ở trẻ bị co giật do sốt đơn thuần?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Tỷ lệ phát hiện tổn thương cấu trúc não nội sọ cần can thiệp ở trẻ co giật do sốt đơn thuần gần như bằng 0%.<br>2) Chụp CT sọ não làm trẻ nhỏ phải chịu bức xạ ion hóa nguy hiểm (làm tăng nguy cơ ung thư não và bạch cầu cấp sau này).<br>3) Chụp MRI đòi hỏi phải dùng thuốc an thần hoặc gây mê ở trẻ nhỏ, tiềm ẩn nguy cơ ức chế hô hấp.<br><br><b>💡 Giải thích của AI:</b><br>Chẩn đoán hình ảnh sọ não chỉ được đặt ra khi trẻ có co giật phức hợp khu trú, có liệt Todd kéo dài, thóp phồng hoặc nghi ngờ tăng áp lực nội sọ.",
        "extra": "📖 Nguồn: AAP 2011 Guideline (Pediatrics 2011, PMID: 21285335)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Cam-CT-MRI-thuong-quy"],
    },
    {
        "id": "PED07-S24",
        "track": "barem_goc",
        "type": "basic",
        "category": "3 chỉ định chọc dò dịch não tủy",
        "section": "S3",
        "front": "Khung 3 tình huống chỉ định chọc dò dịch não tủy (Lumbar Puncture) theo khuyến cáo AAP 2011 ở trẻ co giật do sốt?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) BẮT BUỘC CHỌC: Khi trẻ có bất kỳ dấu hiệu gợi ý viêm màng não hoặc nhiễm trùng thần kinh trung ương (cổ gượng, Kernig (+), Brudzinski (+), thóp phồng, li bì khó đánh thức).<br>2) NÊN CÂN NHẮC ĐẶC BIỆT: Ở trẻ từ 6 đến 12 tháng tuổi chưa được tiêm chủng đầy đủ vaccine Hib và Phế cầu khuẩn (hoặc không rõ tiền sử tiêm chủng).<br>3) NÊN CÂN NHẮC: Ở trẻ đang được điều trị bằng kháng sinh đường toàn thân trước đó (vì kháng sinh có thể làm che lấp các dấu hiệu màng não cổ điển).<br><br><b>💡 Giải thích của AI:</b><br>Ba chỉ định này là kim chỉ nam giúp bác sĩ phòng cấp cứu vừa không bỏ sót viêm màng não mủ chết người, vừa không chọc tủy sống tràn lan gây đau đớn cho trẻ.",
        "extra": "📖 Nguồn: AAP 2011 Guideline (Pediatrics 2011, PMID: 21285335)",
        "tags": ["PED-07", "Barem-goc", "Tong-quan", "3-chi-dinh-choc-DNT"],
    },
    {
        "id": "PED07-S25",
        "track": "barem_goc",
        "type": "basic",
        "category": "Chọc DNT ở trẻ 6-12 tháng",
        "section": "S3",
        "front": "Tại sao trẻ từ 6 đến 12 tháng tuổi bị co giật do sốt lại cần được cân nhắc chọc dịch não tủy kỹ lưỡng hơn trẻ lớn?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Ở lứa tuổi dưới 12 tháng, các triệu chứng kích thích màng não kinh điển (cổ cứng, Kernig, Brudzinski) rất mờ nhạt hoặc hoàn toàn không xuất hiện.<br>2) Viêm màng não mủ ở trẻ nhũ nhi có thể chỉ biểu hiện kín đáo bằng sốt kèm theo cơn co giật đơn độc, bỏ bú hoặc thóp hơi phồng.<br>3) Nếu trẻ chưa được bảo vệ bằng vaccine Hib và Phế cầu 10/13, nguy cơ nhiễm khuẩn huyết xâm lấn màng não là rất cao.<br><br><b>💡 Giải thích của AI:</b><br>Khám lâm sàng âm tính ở trẻ &lt; 12 tháng không bảo đảm 100% loại trừ viêm màng não, do đó việc khai thác tiền sử tiêm chủng là then chốt.",
        "extra": "📖 Nguồn: AAP 2011 Guideline (Pediatrics 2011, PMID: 21285335)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Choc-DNT-tre-duoi-12-thang"],
    },
    {
        "id": "PED07-S26",
        "track": "barem_goc",
        "type": "basic",
        "category": "Kháng sinh che lấp triệu chứng",
        "section": "S3",
        "front": "Tại sao trẻ đã dùng kháng sinh trước đó bị co giật do sốt lại là một chỉ định cần cân nhắc chọc dò thắt lưng?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Kháng sinh uống làm giảm phản ứng viêm toàn thân và phản ứng màng não nhưng chưa đủ nồng độ để tiệt trùng dịch não tủy.<br>2) Làm mất các triệu chứng kinh điển (cổ mềm, không sốt cao vọt) tạo ra bệnh cảnh viêm màng não mất đầu (Decapitated meningitis).<br>3) Hậu quả: Bệnh nhân dễ bị chẩn đoán nhầm là sốt co giật thông thường, dẫn tới chậm trễ điều trị kháng sinh tĩnh mạch liều cao.<br><br><b>💡 Giải thích của AI:</b><br>Hỏi kỹ tiền sử các loại thuốc đã uống trong 48–72 giờ qua là câu hỏi bắt buộc đối với mọi ca co giật do sốt.",
        "extra": "📖 Nguồn: AAP 2011 Guideline (Pediatrics 2011, PMID: 21285335)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Khang-sinh-che-lap-DNT"],
    },
    {
        "id": "PED07-S27",
        "track": "barem_goc",
        "type": "basic",
        "category": "Test đường huyết mao mạch",
        "section": "S3",
        "front": "Vai trò của xét nghiệm đường huyết mao mạch (Dextrostix) ngay tại giường ở bệnh nhi đang co giật là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Phát hiện ngay lập tức tình trạng HẠ ĐƯỜNG HUYẾT NẶNG (&lt; 2,6 mmol/L hay &lt; 45 mg/dL ở trẻ nhỏ).<br>2) Hạ đường huyết là nguyên nhân chuyển hóa gây co giật có thể điều trị khỏi hoàn toàn và tức thì bằng tiêm Glucose tĩnh mạch.<br>3) Nếu không phát hiện hạ đường huyết mà chỉ dùng thuốc chống co giật: Cơn giật không dứt và não sẽ bị tổn thương hoại tử do thiếu đường.<br><br><b>💡 Giải thích của AI:</b><br>Bấm đường huyết mao mạch chỉ mất 5 giây nhưng có thể cứu sống một bộ não. Quy tắc cấp cứu: Bất kỳ trẻ nào co giật hoặc hôn mê đều phải bấm đường huyết ngay lập tức.",
        "extra": "📖 Nguồn: PALS & Advanced Pediatric Life Support (APLS)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Test-duong-huyet-cap-cuu"],
    },
    {
        "id": "PED07-S28",
        "track": "barem_goc",
        "type": "basic",
        "category": "Chẩn đoán phân biệt co giật do sốt",
        "section": "S3",
        "front": "Các hiện tượng lâm sàng không phải động kinh thường bị nhầm lẫn với co giật do sốt ở trẻ nhỏ là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Rùng mình do sốt / Rét run (Rigor): Trẻ run bần bật khi thân nhiệt đang tăng vọt; điểm phân biệt là tri giác hoàn toàn tỉnh táo, khi giữ chặt tay chân thì hết run.<br>2) Cơn nín thở (Breath-holding spells): Xuất hiện sau khi trẻ khóc thét, giận dữ, nín thở tím tái rồi gồng cứng người.<br>3) Co giật do thiếu Canxi (Còi xương): Co thắt bàn tay bàn chân (dấu hiệu bàn tay người đỡ đẻ), thở rít thanh quản.<br>4) Giật cơ khi ngủ (Sleep myoclonus): Giật nhẹ tay chân khi thiu thiu ngủ, hết ngay khi đánh thức trẻ dậy.<br><br><b>💡 Giải thích của AI:</b><br>Hỏi kỹ chi tiết tri giác của trẻ trong lúc xảy ra cơn là chìa khóa: nếu mắt trẻ vẫn nhìn theo mẹ và biết đáp ứng thì chắc chắn không phải co giật toàn thể.",
        "extra": "📖 Nguồn: Nelson Textbook of Pediatrics 21st (Chương Non-epileptic Paroxysmal Disorders)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Phan-biet-khong-dong-kinh"],
    },
    {
        "id": "PED07-S29",
        "track": "barem_goc",
        "type": "basic",
        "category": "Khung lưu đồ cấp cứu AES 2016",
        "section": "S4",
        "front": "Khung 4 mốc thời gian trong lưu đồ cấp cứu trạng thái động kinh theo Hội Động kinh Hoa Kỳ (AES 2016) gồm những gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Mốc 0 – 5 phút (Pha ổn định ban đầu): Đánh giá ABC, cung cấp oxy, đo đường huyết mao mạch, đặt tư thế nằm nghiêng an toàn, bấm giờ cơn giật.<br>2) Mốc 5 – 10 phút (Pha điều trị Bước 1): Dùng thuốc nhóm Benzodiazepine (Midazolam IM/Buccal/IV, Lorazepam IV, hoặc Diazepam PR).<br>3) Mốc 10 – 15 phút: Nếu sau 5 phút vẫn còn giật ➜ Lặp lại liều thứ 2 Benzodiazepine tương tự.<br>4) Mốc 20 – 30 phút (Pha điều trị Bước 2): Nếu cơn giật kéo dài &gt; 15–20 phút ➜ Dùng thuốc chống động kinh đường tĩnh mạch Bước 2 (Levetiracetam, Fosphenytoin, Sodium Valproate).<br>5) Mốc &gt; 40 – 60 phút (Pha điều trị Bước 3): Trạng thái động kinh kháng trị ➜ Đặt nội khí quản, chuyển PICU, dùng thuốc mê truyền liên tục (Midazolam, Propofol, Ketamine, Thiopental).<br><br><b>💡 Giải thích của AI:</b><br>Lưu đồ AES 2016 khóa chặt tư duy cấp cứu theo từng mốc phút, loại bỏ hoàn toàn sự lúng túng chờ đợi và ngăn chặn cơn giật tiến triển thành tổn thương não vĩnh viễn.",
        "extra": "📖 Nguồn: American Epilepsy Society (AES Guidelines 2016, PMID: 26900382)",
        "tags": ["PED-07", "Barem-goc", "Tong-quan", "Luu-do-AES-2016"],
    },
    {
        "id": "PED07-S30",
        "track": "barem_goc",
        "type": "basic",
        "category": "Định nghĩa mốc T1 và T2 theo ILAE",
        "section": "S4",
        "front": "Định nghĩa và ý nghĩa lâm sàng của hai mốc thời gian T1 và T2 trong trạng thái động kinh theo Liên đoàn Chống Động kinh Quốc tế (ILAE 2015)?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Mốc T1 (Thời điểm bắt đầu điều trị cấp cứu = 5 PHÚT đối với cơn co cứng co giật toàn thể): Là mốc mà cơn giật vượt quá thời gian tự ngừng sinh lý, bắt buộc phải dùng thuốc cắt cơn.<br>2) Mốc T2 (Thời điểm bắt đầu xuất hiện tổn thương tế bào não = 30 PHÚT đối với cơn toàn thể): Là mốc mà các cơ chế tự bảo vệ của tế bào thần kinh bị suy sụp, tổn thương nơ ron không hồi phục bắt đầu diễn ra.<br><br><b>💡 Giải thích của AI:</b><br>Khoảng thời gian vàng giữa T1 (5 phút) và T2 (30 phút) chính là cơ hội vàng 25 phút để bác sĩ dập tắt hoàn toàn cơn giật bằng thuốc Bước 1 và Bước 2 trước khi não bị tổn thương.",
        "extra": "📖 Nguồn: ILAE Definition of Status Epilepticus (Epilepsia 2015, PMID: 26338018)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Moc-T1-T2-ILAE"],
    },
    {
        "id": "PED07-S31",
        "track": "barem_goc",
        "type": "basic",
        "category": "Xử trí Mốc 0-5 phút",
        "section": "S4",
        "front": "Chi tiết các hành động cấp cứu bắt buộc trong Mốc 0 – 5 phút đầu tiên khi tiếp nhận trẻ đang co giật?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Bảo đảm an toàn: Đặt trẻ nằm nghiêng sang một bên (tư thế hồi phục) trên mặt phẳng êm, nới lỏng quần áo quanh cổ.<br>2) Hút thông đờm dãi vùng mũi miệng nhẹ nhàng và cho thở oxy qua mask hoặc canula.<br>3) Đánh giá dấu hiệu sinh tồn: Nhịp thở, mạch, SpO₂, nhiệt độ.<br>4) Bấm đường huyết mao mạch ngay lập tức.<br>5) Bấm giờ theo dõi thời gian cơn giật thực tế.<br>6) Chuẩn bị sẵn thuốc Benzodiazepine bước 1 nếu cơn giật tiến gần mốc 5 phút.<br><br><b>💡 Giải thích của AI:</b><br>Tư thế nằm nghiêng là biện pháp tự nhiên tốt nhất để lưỡi không tụt ra sau và dịch nôn trớ chảy ra ngoài, tránh sặc vào phổi.",
        "extra": "📖 Nguồn: PALS & AES 2016 Guidelines (Phase 1 Stabilization)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Xu-tri-0-5-phut"],
    },
    {
        "id": "PED07-S32",
        "track": "barem_goc",
        "type": "basic",
        "category": "Cấm nhét vật cứng vào miệng",
        "section": "S4",
        "front": "Vì sao tuyệt đối cấm nhét thìa, khăn, ngón tay hoặc bất kỳ vật cứng nào vào miệng trẻ đang co giật?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Cắn chặt vật cứng có thể làm gãy răng, tổn thương nướu và niêm mạc miệng của trẻ.<br>2) Răng gãy hoặc dị vật có thể rơi tụt vào khí quản gây tắc nghẽn đường thở cấp tính và ngừng thở.<br>3) Kích thích vùng hầu họng có thể kích hoạt phản xạ nôn ói làm trẻ sặc chất nôn vào phổi gây viêm phổi hít.<br>4) Có thể làm dập nát ngón tay của người sơ cứu.<br><br><b>💡 Giải thích của AI:</b><br>Quan niệm 'sợ trẻ cắn đứt lưỡi' là sai lầm dân gian phổ biến. Trong cơn giật, cơ hàm co cứng chặt nhưng lưỡi chỉ có thể bị cắn rách nhẹ ở bờ bên, không bao giờ tự cắn đứt lưỡi tử vong.",
        "extra": "📖 Nguồn: AAP & Red Cross First Aid for Seizures",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Cam-nhet-vat-vao-mieng"],
    },
    {
        "id": "PED07-S33",
        "track": "barem_goc",
        "type": "basic",
        "category": "Thuốc Bước 1 khi có ven",
        "section": "S4",
        "front": "Lựa chọn thuốc và liều lượng Bước 1 cắt cơn co giật ở trẻ em KHI ĐÃ CÓ ĐƯỜNG TRUYỀN TĨNH MẠCH (IV)?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>Ưu tiên 1 trong 3 thuốc Benzodiazepine tĩnh mạch sau:<br>1) Lorazepam IV: Liều 0,1 mg/kg tiêm TM chậm trong 1–2 phút (tối đa 4 mg).<br>2) Diazepam IV: Liều 0,2 – 0,3 mg/kg tiêm TM chậm trong 2 phút (tối đa 5 mg cho trẻ &lt; 5 tuổi, 10 mg cho trẻ ≥ 5 tuổi).<br>3) Midazolam IV: Liều 0,1 – 0,2 mg/kg tiêm TM chậm trong 2 phút (tối đa 5 mg).<br><br><b>💡 Giải thích của AI:</b><br>Lorazepam là lựa chọn ưu tiên số 1 tại các nước phát triển nhờ thời gian tác dụng duy trì kéo dài (12–24h). Tại Việt Nam, Diazepam và Midazolam là hai thuốc phổ biến nhất.",
        "extra": "📖 Nguồn: AES 2016 Guidelines & Bộ Y tế Việt Nam (Phác đồ cấp cứu co giật)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Thuoc-buoc-1-co-ven"],
    },
    {
        "id": "PED07-S34",
        "track": "barem_goc",
        "type": "basic",
        "category": "Thuốc Bước 1 khi CHƯA có ven",
        "section": "S4",
        "front": "Lựa chọn thuốc và liều lượng Bước 1 cắt cơn co giật ở trẻ em KHI CHƯA THIẾT LẬP ĐƯỢC ĐƯỜNG TRUYỀN TĨNH MẠCH?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) ƯU TIÊN SỐ 1: Midazolam tiêm bắp (IM) liều 0,2 mg/kg tiêm sâu vào mặt trước ngoài đùi (tối đa 10 mg).<br>2) ƯU TIÊN SỐ 2: Midazolam ngậm niêm mạc má (Buccal Midazolam) liều 0,2 – 0,5 mg/kg bơm vào khoang giữa lợi và má (tối đa 10 mg).<br>3) THAY THẾ: Diazepam thụt hậu môn (Rectal Diazepam) liều 0,5 mg/kg (tối đa 10 mg).<br><br><b>💡 Giải thích của AI:</b><br>Theo thử nghiệm RAMPART, Midazolam tiêm bắp ngấm thuốc cực nhanh và cắt cơn nhanh hơn việc mất 5–10 phút loay hoay chọc ven.",
        "extra": "📖 Nguồn: RAMPART Trial (NEJM 2012, PMID: 22335766) & AES 2016",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Thuoc-buoc-1-chua-co-ven"],
    },
    {
        "id": "PED07-S35",
        "track": "barem_goc",
        "type": "basic",
        "category": "Quy tắc 2 liều Benzodiazepine",
        "section": "S4",
        "front": "Quy tắc tối đa 2 liều Benzodiazepine trong cấp cứu cắt cơn co giật ở trẻ em quy định như thế nào và vì sao?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Quy tắc: Chỉ được dùng TỐI ĐA 2 LIỀU Benzodiazepine (cách nhau 5 phút).<br>2) Nếu sau 2 liều mà trẻ vẫn còn co giật: Bắt buộc chuyển ngay sang Thuốc Bước 2 (Levetiracetam / Fosphenytoin / Valproate), tuyệt đối KHÔNG ĐƯỢC tiêm liều Benzodiazepine thứ 3.<br>3) Lý do sống còn: Dùng từ liều thứ 3 trở lên làm tăng vọt nguy cơ ức chế hô hấp, ngừng thở và tụt huyết áp mà hầu như không tăng thêm hiệu quả cắt cơn.<br><br><b>💡 Giải thích của AI:</b><br>Khi cơn giật kéo dài &gt; 15 phút, các thụ thể GABA-A bị thoái hóa biến mất khỏi màng tế bào (Internalization), khiến não bị trơ với Benzodiazepine. Cố tiêm thêm chỉ chuốc lấy ngừng thở.",
        "extra": "📖 Nguồn: AES 2016 Guidelines & PALS Provider Manual",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Quy-tac-2-lieu-Benzo"],
    },
    {
        "id": "PED07-S36",
        "track": "barem_goc",
        "type": "basic",
        "category": "Thuốc Bước 2 Levetiracetam",
        "section": "S4",
        "front": "Liều lượng, cách truyền và ưu điểm của Levetiracetam (Keppra) trong điều trị Bước 2 trạng thái động kinh ở trẻ em?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Liều dùng: 60 mg/kg tiêm truyền tĩnh mạch (tối đa 4500 mg).<br>2) Cách dùng: Pha trong Glucose 5% hoặc NaCl 0,9% truyền tĩnh mạch trong vòng 10 phút.<br>3) Ưu điểm vượt trội: Rất an toàn về huyết động (không gây tụt huyết áp, không gây loạn nhịp tim) và không gây ức chế hô hấp.<br><br><b>💡 Giải thích của AI:</b><br>Thử nghiệm ESETT (2019) chứng minh Levetiracetam có hiệu quả cắt cơn tương đương Fosphenytoin và Valproate nhưng có hồ sơ an toàn tim mạch vượt trội hơn hẳn.",
        "extra": "📖 Nguồn: ESETT Trial (NEJM 2019, PMID: 31778572) & AES 2016",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Thuoc-buoc-2-Levetiracetam"],
    },
    {
        "id": "PED07-S37",
        "track": "barem_goc",
        "type": "basic",
        "category": "Thuốc Bước 2 Fosphenytoin",
        "section": "S4",
        "front": "Liều lượng, tốc độ truyền và lưu ý an toàn khi dùng Fosphenytoin trong Bước 2 trạng thái động kinh?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Liều dùng: 20 mg PE/kg (Phenytoin Equivalent) tiêm truyền tĩnh mạch (tối đa 1500 mg PE).<br>2) Tốc độ truyền tối đa: Không vượt quá 150 mg PE/phút (ở trẻ em không quá 2 mg PE/kg/phút).<br>3) Lưu ý an toàn bắt buộc: Bắt buộc gắn monitor theo dõi điện tâm đồ (ECG) và huyết áp liên tục trong suốt quá trình truyền vì nguy cơ tụt huyết áp và loạn nhịp tim (khoảng QT kéo dài, block nhĩ thất).<br><br><b>💡 Giải thích của AI:</b><br>Fosphenytoin là tiền chất tan trong nước của Phenytoin, ít gây hoại tử mô hơn Phenytoin cũ nhưng vẫn có nguy cơ độc tính tim mạch do ức chế kênh Natri.",
        "extra": "📖 Nguồn: AES 2016 Guidelines & ESETT Trial",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Thuoc-buoc-2-Fosphenytoin"],
    },
    {
        "id": "PED07-S38",
        "track": "barem_goc",
        "type": "basic",
        "category": "Thuốc Bước 2 Sodium Valproate",
        "section": "S4",
        "front": "Liều lượng, cách dùng và chống chỉ định quan trọng của Sodium Valproate (Depakine) trong Bước 2 trạng thái động kinh?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Liều dùng: 40 mg/kg tiêm truyền tĩnh mạch (tối đa 3000 mg).<br>2) Cách dùng: Truyền tĩnh mạch trong vòng 10 phút.<br>3) Chống chỉ định quan trọng: Chống chỉ định ở trẻ nghi ngờ mắc bệnh lý chuyển hóa ty thể (đặc biệt hội chứng Alpers do đột biến gen POLG), trẻ dưới 2 tuổi có suy gan hoặc rối loạn chu trình urê.<br><br><b>💡 Giải thích của AI:</b><br>Valproate ức chế quá trình oxy hóa beta của acid béo trong ty thể. Dùng cho trẻ có bệnh ty thể tiềm ẩn có thể gây suy gan tối cấp tử vong.",
        "extra": "📖 Nguồn: ESETT Trial & AES 2016 Guidelines",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Thuoc-buoc-2-Valproate"],
    },
    {
        "id": "PED07-S39",
        "track": "barem_goc",
        "type": "basic",
        "category": "Trạng thái động kinh kháng trị Bước 3",
        "section": "S4",
        "front": "Định nghĩa Trạng thái động kinh kháng trị (RSE - Bước 3) và các biện pháp can thiệp hồi sức chuyên sâu?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Định nghĩa RSE: Cơn co giật vẫn tiếp diễn sau khi đã dùng đủ 1 liều Benzodiazepine Bước 1 và 1 liều thuốc chống động kinh Bước 2 (thường kéo dài &gt; 30–60 phút).<br>2) Can thiệp hồi sức bắt buộc:<br>- Đặt ống nội khí quản thở máy xâm lấn bảo vệ đường thở.<br>- Chuyển ngay vào khoa Hồi sức tích cực Nhi (PICU).<br>- Dùng thuốc mê truyền tĩnh mạch liên tục: Midazolam truyền liên tục (0,1–2 mg/kg/h), Propofol, Ketamine hoặc Thiopental.<br>- Gắn điện não đồ liên tục (cEEG) nhằm đạt mục tiêu ức chế bùng phát (Burst suppression) trong 24–48 giờ.<br><br><b>💡 Giải thích của AI:</b><br>Ở giai đoạn RSE, thuốc mê truyền liên tục là vũ khí duy nhất dập tắt các ổ phóng điện bão hòa trong vỏ não.",
        "extra": "📖 Nguồn: Neurocritical Care Society Guidelines on Status Epilepticus",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "RSE-buoc-3"],
    },
    {
        "id": "PED07-S40",
        "track": "barem_goc",
        "type": "basic",
        "category": "Mục tiêu Burst Suppression",
        "section": "S4",
        "front": "Mục tiêu 'Ức chế bùng phát' (Burst Suppression) trên điện não đồ liên tục (cEEG) trong điều trị trạng thái động kinh kháng trị là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Khái niệm: Là trạng thái điện não đồ nhân tạo được tạo ra bởi thuốc mê liều cao, đặc trưng bởi các đợt sóng điện não ngắn (Burst) xen kẽ với các khoảng đẳng điện hoàn toàn phẳng lặng (Suppression) kéo dài từ 5 đến 15 giây.<br>2) Tỷ lệ mục tiêu: Duy trì khoảng 80% đến 90% thời gian là sóng phẳng (ức chế).<br>3) Thời gian duy trì: Duy trì liên tục trong 24 đến 48 giờ trước khi bắt đầu giảm liều thuốc mê dần dần.<br><br><b>💡 Giải thích của AI:</b><br>Đưa não vào trạng thái 'ngủ đông điện học' giúp tế bào thần kinh có thời gian nghỉ ngơi, phục hồi dự trữ ATP và chấm dứt chuỗi tổn thương độc tế bào.",
        "extra": "📖 Nguồn: American Clinical Neurophysiology Society (cEEG Guidelines)",
        "tags": ["PED-07", "Barem-goc", "Chi-tiet", "Burst-Suppression-cEEG"],
    },
    {
        "id": "PED07-S41",
        "track": "ebm",
        "type": "basic",
        "category": "Dược lý Midazolam",
        "section": "S5",
        "front": "Cơ chế tác dụng phân tử của Midazolam trên thụ thể GABA-A và ưu điểm dược động học của nó là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Cơ chế phân tử: Gắn chọn lọc vào vị trí Benzodiazepine trên thụ thể GABA-A, làm tăng tần số mở kênh ion Cl⁻ ➜ Gây ưu phân cực màng nơ ron và dập tắt phóng điện kịch phát.<br>2) Ưu điểm dược động học: Tan tốt trong nước ở pH acid (trong lọ thuốc) nên không gây đau khi tiêm bắp; tan rất tốt trong mỡ ở pH sinh lý của máu (pH 7,4) nên vượt qua hàng rào máu não cực nhanh.<br>3) Thời gian khởi phát tác dụng: Cắt cơn trong vòng 1 – 3 phút sau tiêm bắp hoặc ngậm niêm mạc má.<br><br><b>💡 Giải thích của AI:</b><br>Đặc tính 'lưỡng tính theo pH' độc đáo biến Midazolam thành thuốc chống co giật linh hoạt và hiệu quả hàng đầu trong cấp cứu tiền viện và buồng bệnh.",
        "extra": "📖 Nguồn: Goodman & Gilman's Pharmacological Basis of Therapeutics (Benzodiazepines)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Duoc-ly-Midazolam"],
    },
    {
        "id": "PED07-S42",
        "track": "ebm",
        "type": "basic",
        "category": "Kỹ thuật dùng Midazolam ngậm má",
        "section": "S5",
        "front": "Kỹ thuật dùng Midazolam ngậm niêm mạc má (Buccal Midazolam) ở trẻ em quy định vị trí bơm và lưu ý an toàn như thế nào?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Liều lượng: 0,2 – 0,5 mg/kg (tối đa 10 mg), dùng bơm tiêm không kim.<br>2) Vị trí bơm thuốc: Bơm từ từ vào KHOANG GIỮA LỢI VÀ MÁ (Buccal cavity) của trẻ (có thể chia đều hai bên má).<br>3) Lưu ý an toàn sống còn: TUYỆT ĐỐI KHÔNG BƠM TRỰC TIẾP VÀO SÂU TRONG HỌNG để tránh kích thích phản xạ co thắt thanh quản hoặc làm trẻ hít sặc thuốc vào đường thở.<br><br><b>💡 Giải thích của AI:</b><br>Niêm mạc má có mạng lưới mao mạch phong phú, thuốc hấp thu trực tiếp vào hệ tuần hoàn tĩnh mạch mà không bị chuyển hóa qua gan lần đầu, đạt nồng độ đỉnh trong máu rất nhanh.",
        "extra": "📖 Nguồn: British National Formulary for Children (BNFC - Buccal Midazolam)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Midazolam-ngam-ma"],
    },
    {
        "id": "PED07-S43",
        "track": "ebm",
        "type": "basic",
        "category": "Diazepam bơm hậu môn",
        "section": "S5",
        "front": "Liều dùng, cách dùng và nhược điểm của Diazepam bơm hậu môn (Rectal Diazepam) trong cắt cơn co giật ở trẻ em?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Liều dùng: 0,5 mg/kg bơm trực tràng (ống tuýp chuyên dụng hoặc dùng bơm tiêm gắn ống thông nhỏ đưa sâu 2–3 cm).<br>2) Kỹ thuật: Bơm dứt khoát thuốc vào trực tràng, sau đó giữ ép chặt hai cánh mông của trẻ trong 2–3 phút để thuốc không bị trào ngược ra ngoài.<br>3) Nhược điểm so với Midazolam: Hấp thu thất thường nếu trực tràng có phân; thao tác tụt quần trẻ ở nơi công cộng gây bất tiện tâm lý cho gia đình; nguy cơ suy hô hấp kéo dài hơn do thời gian bán thải dài (20–50 giờ).<br><br><b>💡 Giải thích của AI:</b><br>Hiện nay các guideline quốc tế (như NICE và AES) đã xếp Midazolam ngậm má hoặc tiêm bắp lên vị trí ưu tiên hơn Diazepam bơm hậu môn.",
        "extra": "📖 Nguồn: AES 2016 Guidelines & Cochrane Database of Systematic Reviews",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Diazepam-bom-hau-mon"],
    },
    {
        "id": "PED07-S44",
        "track": "ebm",
        "type": "basic",
        "category": "Dược lý Levetiracetam",
        "section": "S5",
        "front": "Cơ chế tác dụng độc đáo của Levetiracetam (Keppra) qua protein SV2A và lý do thuốc được ưa chuộng nhất trong Bước 2?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Cơ chế tác dụng: Gắn chọn lọc vào protein bóng túi synap SV2A (Synaptic Vesicle Protein 2A) ➜ Ức chế giải phóng các chất dẫn truyền thần kinh kích thích (Glutamate) vào khe synap.<br>2) Lý do được ưa chuộng nhất trong Bước 2:<br>- Không gây ức chế co bóp cơ tim hay tụt huyết áp.<br>- Không gây ức chế hô hấp (an toàn khi dùng sau Benzodiazepine).<br>- Có thể truyền nhanh trong 10 phút mà không cần monitor huyết động phức tạp như Phenytoin.<br>- Không có tương tác thuốc và không độc với gan.<br><br><b>💡 Giải thích của AI:</b><br>Nhờ cơ chế SV2A độc lập với các kênh ion thông thường, Levetiracetam mang lại hiệu quả cắt cơn tương đương các thuốc cổ điển nhưng có độ an toàn vượt trội.",
        "extra": "📖 Nguồn: ESETT Study (NEJM 2019) & Pharmacotherapy of Status Epilepticus",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Duoc-ly-Levetiracetam"],
    },
    {
        "id": "PED07-S45",
        "track": "ebm",
        "type": "basic",
        "category": "Dược lý Fosphenytoin",
        "section": "S5",
        "front": "Cơ chế tác dụng của Fosphenytoin trên kênh Natri và các cạm bẫy độc tính tim mạch cần giám sát?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Cơ chế: Gắn vào trạng thái bất hoạt của kênh Natri phụ thuộc điện thế (Voltage-gated Sodium channels) trên màng nơ ron, làm kéo dài thời gian trơ và ngăn chặn khử cực tần số cao.<br>2) Cạm bẫy độc tính tim mạch:<br>- Gây tụt huyết áp nghiêm trọng nếu truyền quá nhanh.<br>- Gây chậm nhịp tim, kéo dài khoảng QT, block nhĩ thất và vô tâm thu.<br>➜ Bắt buộc phải cài đặt tốc độ truyền không quá 150 mg PE/phút và theo dõi monitor ECG liên tục.<br><br><b>💡 Giải thích của AI:</b><br>Fosphenytoin chống chỉ định tuyệt đối ở bệnh nhân có block nhĩ thất độ II-III hoặc nhịp chậm xoang nặng.",
        "extra": "📖 Nguồn: AES 2016 Guidelines & Cardiovascular Safety of Antiepileptics",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Duoc-ly-Fosphenytoin"],
    },
    {
        "id": "PED07-S46",
        "track": "ebm",
        "type": "basic",
        "category": "Dược lý Sodium Valproate",
        "section": "S5",
        "front": "Cơ chế đa phương thức của Sodium Valproate và nguy cơ viêm gan nhiễm độc ở trẻ nhỏ dưới 2 tuổi?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Cơ chế đa phương thức: Vừa chẹn kênh Natri, vừa tăng nồng độ GABA trong não (ức chế enzyme GABA-transaminase), vừa chẹn kênh Canxi loại T.<br>2) Nguy cơ viêm gan nhiễm độc: Trẻ dưới 2 tuổi (đặc biệt khi có đa dị tật hoặc chậm phát triển) có nguy cơ cao bị độc gan tối cấp và viêm tụy cấp.<br>3) Chống chỉ định tuyệt đối: Bệnh nhân có đột biến gen POLG (Hội chứng Alpers-Huttenlocher) hoặc rối loạn chu trình urê.<br><br><b>💡 Giải thích của AI:</b><br>Nếu trẻ có biểu hiện chậm phát triển tâm vận từ trước kèm gan to hoặc tăng amoniac máu, nên chọn Levetiracetam thay vì Valproate.",
        "extra": "📖 Nguồn: FDA Black Box Warning & Pediatric Neurology",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Duoc-ly-Valproate"],
    },
    {
        "id": "PED07-S47",
        "track": "ebm",
        "type": "basic",
        "category": "Thuốc mê Bước 3 Midazolam truyền",
        "section": "S5",
        "front": "Phác đồ sử dụng Midazolam truyền tĩnh mạch liên tục trong Bước 3 trạng thái động kinh kháng trị (RSE)?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Liều nạp (Bolus): 0,2 mg/kg tiêm tĩnh mạch chậm trong 2 phút.<br>2) Liều duy trì: Bắt đầu truyền liên tục ở liều 0,1 mg/kg/giờ (khoảng 1,5–2 µg/kg/phút).<br>3) Chỉnh liều: Tăng liều mỗi 15 phút (thêm 0,05–0,1 mg/kg/giờ) cho đến khi dứt hoàn toàn cơn giật trên lâm sàng và đạt mục tiêu kiểm soát trên EEG (tối đa có thể lên tới 1–2 mg/kg/giờ).<br><br><b>💡 Giải thích của AI:</b><br>Midazolam truyền liên tục có ưu điểm là thời gian bán thải ngắn, ít gây tích tụ thuốc và phục hồi nhanh hơn Thiopental khi ngừng truyền.",
        "extra": "📖 Nguồn: Neurocritical Care Society Guidelines (RSE Management)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Midazolam-truyen-lien-tuc"],
    },
    {
        "id": "PED07-S48",
        "track": "ebm",
        "type": "basic",
        "category": "Cảnh báo Hội chứng PRIS của Propofol",
        "section": "S5",
        "front": "Cảnh báo sống còn về Hội chứng truyền Propofol (PRIS - Propofol Infusion Syndrome) ở trẻ em trong hồi sức động kinh?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) PRIS là hội chứng nhiễm độc cấp đe dọa tử vong khi truyền Propofol liều cao (&gt; 4–5 mg/kg/h) hoặc kéo dài &gt; 48 giờ ở trẻ em.<br>2) Biểu hiện kinh điển: Toan chuyển hóa nặng kháng trị, tiêu cơ vân (tăng Creatine Kinase vọt), suy tim cấp, tụt huyết áp trơ vận mạch, tăng mỡ máu và suy thận cấp.<br>3) Khuyến cáo: Hạn chế dùng Propofol truyền kéo dài ở trẻ em; nếu dùng bắt buộc phải dùng liều thấp (&lt; 4 mg/kg/h) và không quá 24–48 giờ.<br><br><b>💡 Giải thích của AI:</b><br>Tỷ lệ tử vong của hội chứng PRIS lên tới trên 50%. Đây là lý do Midazolam hoặc Ketamine thường được ưu tiên hơn Propofol trong hồi sức trạng thái động kinh nhi.",
        "extra": "📖 Nguồn: FDA Warning & Critical Care Medicine (Propofol Infusion Syndrome in Children)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Hoi-chung-PRIS-Propofol"],
    },
    {
        "id": "PED07-S49",
        "track": "ebm",
        "type": "basic",
        "category": "Vai trò của Ketamine trong RSE",
        "section": "S5",
        "front": "Cơ chế phân tử độc đáo nào khiến Ketamine trở thành vũ khí cứu cánh trong trạng thái động kinh kháng trị kéo dài?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Khi cơn giật kéo dài &gt; 30–60 phút, các thụ thể GABA bị thoái hóa nội bào (mất tác dụng với Benzodiazepine), trong khi các thụ thể NMDA kích thích lại tăng biểu hiện mạnh mẽ trên màng tế bào.<br>2) Ketamine là chất đối kháng không cạnh tranh chọn lọc trên thụ thể NMDA.<br>3) Thuốc trực tiếp khóa dòng ion Canxi qua kênh NMDA, dập tắt vòng kích thích độc tế bào Glutamate và duy trì huyết động ổn định nhờ kích thích giao cảm nhẹ.<br><br><b>💡 Giải thích của AI:</b><br>Ketamine đánh trúng đích vào cơ chế bệnh sinh của trạng thái động kinh giai đoạn muộn, là thuốc cứu cánh khi Midazolam và Barbiturate thất bại.",
        "extra": "📖 Nguồn: Neuropharmacology & Pediatric Critical Care (Ketamine in Super-refractory SE)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Ketamine-trong-RSE"],
    },
    {
        "id": "PED07-S50",
        "track": "ebm",
        "type": "basic",
        "category": "Thiopental / Pentobarbital",
        "section": "S5",
        "front": "Chỉ định và độc tính tim mạch của Thiopental / Pentobarbital trong điều trị trạng thái động kinh kháng trị siêu kháng (SRSE)?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Chỉ định: Là vũ khí cuối cùng khi mọi thuốc mê khác (Midazolam, Ketamine) thất bại.<br>2) Cơ chế: Kích hoạt trực tiếp kênh Cl⁻ trên thụ thể GABA-A ngay cả khi không có GABA nội sinh, ức chế chuyển hóa não tối đa.<br>3) Độc tính tim mạch nặng nề: Gây tụt huyết áp nghiêm trọng do ức chế trực tiếp cơ tim và giãn mạch thụ động, liệt ruột và ức chế miễn dịch ➜ Bắt buộc phải đặt catheter động mạch xâm lấn và phối hợp thuốc vận mạch (Noradrenaline / Adrenaline).<br><br><b>💡 Giải thích của AI:</b><br>Thiopental tích tụ trong mô mỡ nên thời gian bán thải kéo dài nhiều ngày sau khi ngừng truyền, đòi hỏi thời gian cai máy thở rất lâu.",
        "extra": "📖 Nguồn: Pediatric Neurocritical Care (Barbiturate Coma Protocol)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Thiopental-SRSE"],
    },
    {
        "id": "PED07-S51",
        "track": "ebm",
        "type": "basic",
        "category": "RAMPART Trial",
        "section": "S6",
        "front": "Thiết kế và kết quả bước ngoặt của thử nghiệm lâm sàng RAMPART (NEJM 2012, PMID: 22335766) là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Thiết kế: Thử nghiệm ngẫu nhiên mù đôi đối chứng (n = 893 bệnh nhân động kinh co giật tiền viện), so sánh Midazolam tiêm bắp (IM) với Lorazepam tiêm tĩnh mạch (IV).<br>2) Kết quả: Nhóm Midazolam IM có tỷ lệ dứt cơn co giật trước khi đến phòng cấp cứu cao hơn (73,4% so với 63,4%, p &lt; 0,001).<br>3) Tốc độ cắt cơn: Thời gian từ khi bắt đầu xử trí đến khi dứt cơn ở nhóm Midazolam IM nhanh hơn đáng kể (do không mất thời gian tìm ven).<br>4) Tác dụng phụ: Tỷ lệ đặt nội khí quản và suy hô hấp tương đương nhau.<br><br><b>💡 Giải thích của AI:</b><br>RAMPART đã thay đổi hoàn toàn hướng dẫn cấp cứu toàn cầu: Midazolam tiêm bắp trở thành lựa chọn hàng đầu ngoài bệnh viện và phòng khám khi chưa có ven.",
        "extra": "📖 Nguồn: Silbergleit R et al., RAMPART Investigators, NEJM 2012 (PMID: 22335766)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "RAMPART-Trial"],
    },
    {
        "id": "PED07-S52",
        "track": "ebm",
        "type": "basic",
        "category": "ESETT Trial",
        "section": "S6",
        "front": "Nghiên cứu ESETT (NEJM 2019, PMID: 31778572) đưa ra kết luận then chốt gì khi so sánh 3 thuốc chống động kinh Bước 2?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Thiết kế: Thử nghiệm ngẫu nhiên mù đôi đa trung tâm so sánh Levetiracetam (60 mg/kg), Fosphenytoin (20 mg PE/kg) và Sodium Valproate (40 mg/kg) ở bệnh nhân trạng thái động kinh kháng Benzodiazepine.<br>2) Kết quả hiệu quả: Cả 3 thuốc có tỷ lệ cắt cơn thành công tương đương nhau (khoảng 47% ở Levetiracetam, 45% ở Fosphenytoin, 46% ở Valproate, không có khác biệt có ý nghĩa thống kê).<br>3) Kết quả an toàn: Levetiracetam có tỷ lệ biến chứng tim mạch và suy hô hấp thấp nhất.<br><br><b>💡 Giải thích của AI:</b><br>ESETT chứng minh cả 3 thuốc đều là lựa chọn Bước 2 hợp lệ, nhưng Levetiracetam được ưa chuộng hơn trong thực hành nhi khoa nhờ tính an toàn vượt trội.",
        "extra": "📖 Nguồn: Kapur J et al., ESETT Trial Investigators, NEJM 2019 (PMID: 31778572)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "ESETT-Trial"],
    },
    {
        "id": "PED07-S53",
        "track": "ebm",
        "type": "basic",
        "category": "FEBSTAT Study",
        "section": "S6",
        "front": "Nghiên cứu đoàn hệ FEBSTAT (Epilepsia 2012 / 2025, PMID: 22841663 / 40770931) phát hiện tổn thương thần kinh nào ở trẻ bị FSE kéo dài?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Chụp MRI sọ não trong 72 giờ đầu sau cơn FSE: Ghi nhận 11,5% trẻ có tổn thương tăng tín hiệu T2/FLAIR cấp tính tại HỒI HẢI MÃ (Hippocampus).<br>2) Theo dõi dài hạn sau 10–15 năm: Nhóm có tổn thương cấp tính này có nguy cơ tiến triển thành XƠ HÓA HỒI HẢI MÃ (Hippocampal Sclerosis) và phát triển bệnh Động kinh thùy thái dương kháng trị.<br>3) Yếu tố liên quan: Cơn giật kéo dài trên 30–60 phút và cơn giật có tính chất cục bộ là hai yếu tố nguy cơ hàng đầu.<br><br><b>💡 Giải thích của AI:</b><br>Dữ liệu FEBSTAT là lời cảnh tỉnh mạnh mẽ nhất: Trạng thái động kinh do sốt kéo dài không còn là biến cố lành tính mà là một tình trạng tổn thương não thực thể.",
        "extra": "📖 Nguồn: Shinnar S et al., FEBSTAT Study, Epilepsia 2012 & Epilepsia Open 2025",
        "tags": ["PED-07", "EBM", "Chi-tiet", "FEBSTAT-Study"],
    },
    {
        "id": "PED07-S54",
        "track": "ebm",
        "type": "basic",
        "category": "ConSEPT & EcLiPSE Trials",
        "section": "S6",
        "front": "Hai thử nghiệm lâm sàng ConSEPT và EcLiPSE (Lancet 2019, PMID: 31128945 / 31128944) so sánh Levetiracetam và Phenytoin ở trẻ em cho kết quả gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Thiết kế: Hai thử nghiệm ngẫu nhiên độc lập tại Úc/New Zealand (ConSEPT) và Vương quốc Anh (EcLiPSE) so sánh Levetiracetam 40 mg/kg với Phenytoin 20 mg/kg ở trẻ em trạng thái động kinh.<br>2) Kết quả: Hiệu quả cắt cơn của Levetiracetam tương đương với Phenytoin (khoảng 50–60%).<br>3) Thời gian chuẩn bị và truyền thuốc: Levetiracetam pha truyền nhanh hơn, ít gặp tác dụng phụ tim mạch hơn và được điều dưỡng đánh giá dễ sử dụng hơn.<br><br><b>💡 Giải thích của AI:</b><br>Bộ đôi ConSEPT và EcLiPSE đã thúc đẩy Levetiracetam vươn lên trở thành thuốc Bước 2 được kê đơn phổ biến nhất tại các khoa hồi sức cấp cứu nhi trên toàn cầu.",
        "extra": "📖 Nguồn: Dalziel SR et al. (ConSEPT) & Lyttle MD et al. (EcLiPSE), Lancet 2019",
        "tags": ["PED-07", "EBM", "Chi-tiet", "ConSEPT-EcLiPSE-2019"],
    },
    {
        "id": "PED07-S55",
        "track": "ebm",
        "type": "basic",
        "category": "Khuyến cáo AAP 2008 về thuốc dự phòng",
        "section": "S6",
        "front": "Khuyến cáo của Viện Hàn lâm Nhi khoa Hoa Kỳ (AAP 2008, PMID: 18310189) về việc sử dụng thuốc chống động kinh dự phòng thường quy ở trẻ co giật do sốt đơn thuần là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Khuyến cáo chính thức: KHÔNG SỬ DỤNG thuốc chống động kinh liên tục (Phenobarbital, Valproate) hoặc ngắt quãng (Diazepam uống) thường quy để dự phòng tái phát co giật do sốt đơn thuần.<br>2) Lý do 1: Dù Phenobarbital và Valproate có thể giảm tỷ lệ tái phát cơn giật do sốt, nhưng chúng HOÀN TOÀN KHÔNG NGĂN NGỪA ĐƯỢC nguy cơ phát triển thành bệnh động kinh thực sự sau này.<br>3) Lý do 2: Tác dụng phụ nghiêm trọng của thuốc (giảm trí nhớ, tăng động, rối loạn hành vi, độc tính gan của Valproate) vượt xa nguy cơ lành tính của một cơn co giật do sốt đơn thuần.<br><br><b>💡 Giải thích của AI:</b><br>Nguyên tắc y đạo: 'Không dùng một biện pháp điều trị có hại lớn hơn căn bệnh lành tính cần điều trị'.",
        "extra": "📖 Nguồn: AAP Steering Committee on Quality Improvement, Pediatrics 2008 (PMID: 18310189)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "AAP-2008-Cam-du-phong"],
    },
    {
        "id": "PED07-S56",
        "track": "ebm",
        "type": "basic",
        "category": "Tỷ lệ tái phát co giật do sốt",
        "section": "S7",
        "front": "Tỷ lệ tái phát cơn co giật do sốt ở trẻ em nói chung là bao nhiêu và nguy cơ tập trung trong khoảng thời gian nào?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Tỷ lệ tái phát chung: Khoảng 30% đến 35% trẻ bị co giật do sốt lần đầu sẽ bị tái phát ít nhất một cơn trong các đợt sốt tiếp theo.<br>2) Tỷ lệ tái phát từ 2 lần trở lên: Chỉ khoảng 10% trẻ.<br>3) Thời điểm tái phát: Hơn 75% các cơn tái phát xảy ra trong vòng 1 năm đầu tiên kể từ cơn giật đầu tiên.<br><br><b>💡 Giải thích của AI:</b><br>Nghĩa là gần 70% trẻ sẽ không bao giờ bị giật lại nữa sau cơn đầu tiên. Giải thích con số này giúp xoa dịu nỗi ám ảnh sợ hãi của cha mẹ.",
        "extra": "📖 Nguồn: Nelson Textbook of Pediatrics 21st (Chương Prognosis of Febrile Seizures)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Ty-le-tai-phat"],
    },
    {
        "id": "PED07-S57",
        "track": "ebm",
        "type": "basic",
        "category": "4 yếu tố nguy cơ tái phát",
        "section": "S7",
        "front": "Bốn yếu tố nguy cơ chính làm tăng tỷ lệ tái phát cơn co giật do sốt ở trẻ em là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Khởi phát cơn giật đầu tiên ở lứa tuổi còn rất nhỏ (&lt; 12 – 18 tháng tuổi) ➜ Yếu tố nguy cơ mạnh nhất (tỷ lệ tái phát lên tới 50%).<br>2) Tiền sử gia đình có người thân trực hệ (bố, mẹ, anh chị em ruột) từng bị co giật do sốt.<br>3) Cơn co giật xảy ra ở mức nhiệt độ sốt thấp (&lt; 38,5°C).<br>4) Thời gian từ lúc khởi phát sốt đến khi xuất hiện cơn giật rất ngắn (&lt; 1 giờ).<br><br><b>💡 Giải thích của AI:</b><br>Trẻ có đủ cả 4 yếu tố trên có tỷ lệ tái phát lên tới 70%, trong khi trẻ không có yếu tố nào chỉ có tỷ lệ tái phát dưới 15%.",
        "extra": "📖 Nguồn: AAP 2008 Guideline & Berg AT et al. (Predictors of Recurrent Febrile Seizures)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Yeu-to-nguy-co-tai-phat"],
    },
    {
        "id": "PED07-S58",
        "track": "ebm",
        "type": "basic",
        "category": "Nguy cơ tiến triển thành động kinh",
        "section": "S7",
        "front": "Nguy cơ tiến triển thành bệnh Động kinh thực sự (Epilepsy) sau co giật do sốt là bao nhiêu và các yếu tố nguy cơ đi kèm?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Ở trẻ co giật do sốt ĐƠN THUẦN: Nguy cơ chỉ khoảng 1% đến 2% (gần như tương đương với tỷ lệ mắc động kinh trong dân số trẻ em bình thường là 0,5–1%).<br>2) Các yếu tố làm tăng nguy cơ phát triển thành động kinh (lên tới 5–10% hoặc cao hơn):<br>- Có bất thường phát triển thần kinh hoặc chậm phát triển tâm thần vận động từ trước.<br>- Cơn co giật do sốt mang tính chất PHỨC HỢP (đặc biệt là cơn cục bộ hoặc kéo dài).<br>- Tiền sử gia đình có người thân trực hệ mắc bệnh động kinh không do sốt.<br><br><b>💡 Giải thích của AI:</b><br>Trấn an gia đình: Nếu trẻ hoàn toàn bình thường và chỉ bị co giật do sốt đơn thuần, nguy cơ bị động kinh sau này là cực kỳ thấp.",
        "extra": "📖 Nguồn: AAP Practice Guideline & Nelson Pediatrics",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Nguy-co-dong-kinh"],
    },
    {
        "id": "PED07-S59",
        "track": "ebm",
        "type": "basic",
        "category": "Hướng dẫn xử trí tại nhà cho phụ huynh",
        "section": "S7",
        "front": "Nội dung hướng dẫn xử trí cơn co giật tại nhà chuẩn khoa học dành cho phụ huynh (Checklist 5 nên - 5 không)?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>5 NÊN:<br>1) Giữ bình tĩnh, đặt trẻ nằm nghiêng sang một bên trên mặt phẳng an toàn.<br>2) Nới lỏng cổ áo, thắt lưng, bỏ kính mắt nếu có.<br>3) Bấm giờ chính xác thời gian cơn giật kéo dài.<br>4) Dọn dẹp các vật cứng, sắc nhọn xung quanh.<br>5) Gọi cấp cứu 115 ngay nếu cơn giật kéo dài quá 5 phút hoặc sau cơn trẻ không tỉnh.<br>5 KHÔNG TUYỆT ĐỐI:<br>1) Không nhét bất kỳ vật gì vào miệng.<br>2) Không đè ép, ghì chặt chân tay trẻ.<br>3) Không cho uống nước, sữa hay thuốc khi đang giật.<br>4) Không vắt chanh vào miệng hoặc giật tóc, bấm nhân trung.<br>5) Không bế xốc trẻ chạy vòng quanh.<br><br><b>💡 Giải thích của AI:</b><br>Bản hướng dẫn này là tấm lá chắn bảo vệ an toàn cho trẻ tại nhà, xóa bỏ hoàn toàn các hủ tục gây hại đường thở.",
        "extra": "📖 Nguồn: AAP Parent Information & Epilepsy Foundation First Aid",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Huong-dan-tai-nha"],
    },
    {
        "id": "PED07-S60",
        "track": "ebm",
        "type": "basic",
        "category": "Sử dụng thuốc hạ sốt",
        "section": "S7",
        "front": "Bằng chứng y học về việc dùng thuốc hạ sốt (Paracetamol, Ibuprofen) trong phòng ngừa cơn co giật do sốt tái phát là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Bằng chứng từ các thử nghiệm lâm sàng: Thuốc hạ sốt KHÔNG CÓ TÁC DỤNG NGĂN NGỪA cơn co giật do sốt khởi phát hoặc tái phát.<br>2) Mục đích thực sự của thuốc hạ sốt: Giúp trẻ dễ chịu, giảm đau mỏi người, hạ thân nhiệt để giảm mất nước vô hình, không phải là thuốc chống co giật.<br>3) Cảnh báo: Tuyệt đối không phối hợp quá liều hoặc dùng dồn dập thuốc hạ sốt vì nguy cơ ngộ độc gan cấp do Paracetamol.<br><br><b>💡 Giải thích của AI:</b><br>Nhiều cơn giật xảy ra ngay khi thân nhiệt vừa mới bắt đầu tăng vọt trước khi phụ huynh kịp nhận biết trẻ sốt, do đó thuốc hạ sốt không thể chặn trước được cơn giật.",
        "extra": "📖 Nguồn: Cochrane Systematic Review (Antipyretics for Febrile Seizures) & AAP 2008",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Ha-sot-va-co-giat"],
    },
    {
        "id": "PED07-S61",
        "track": "ebm",
        "type": "basic",
        "category": "Bẫy chờ chọc ven ngoại vi",
        "section": "S8",
        "front": "Cạm bẫy lâm sàng số 1: Vì sao chờ đợi chọc ven tĩnh mạch thay vì dùng ngay Midazolam tiêm bắp là một sai lầm chết người tại phòng cấp cứu?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Trẻ đang co giật chân tay gồng cứng, mạch máu co thắt làm việc chọc ven ngoại vi thường mất từ 5 đến 15 phút, tỷ lệ thất bại rất cao.<br>2) Trong thời gian chờ chọc ven, cơn co giật kéo dài liên tục làm tiêu hao năng lượng não và tiến gần tới mốc tổn thương T2 (30 phút).<br>3) Thử nghiệm RAMPART chứng minh Midazolam tiêm bắp ngấm nhanh tương đương tiêm ven và cắt cơn sớm hơn việc chờ chọc ven tới 10 phút.<br><br><b>💡 Giải thích của AI:</b><br>Quy tắc vàng: Nếu chưa có ven sẵn, TIÊM BẮP MIDAZOLAM NGAY LẬP TỨC. Có thể vừa tiêm bắp vừa thiết lập đường truyền sau đó.",
        "extra": "📖 Nguồn: PALS & RAMPART Trial (NEJM 2012)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Bay-cho-choc-ven"],
    },
    {
        "id": "PED07-S62",
        "track": "ebm",
        "type": "basic",
        "category": "Bẫy lạm dụng Benzodiazepine",
        "section": "S8",
        "front": "Cạm bẫy lâm sàng số 2: Hậu quả của việc tiêm liều Benzodiazepine thứ 3 hoặc thứ 4 khi cơn giật chưa dứt là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Nguy cơ suy hô hấp cấp, tụt lưỡi và ngừng thở tăng vọt (chiếm tới hơn 30% các ca dùng từ 3 liều trở lên).<br>2) Tụt huyết áp và mất phản xạ bảo vệ đường thở.<br>3) Cơ chế phân tử: Lúc này các thụ thể GABA-A đã bị thoái hóa nội bào (Receptor Internalization), tế bào não bị trơ với Benzodiazepine nên tiêm thêm hoàn toàn không có tác dụng cắt cơn.<br><br><b>💡 Giải thích của AI:</b><br>Luôn dừng lại ở liều thứ 2 Benzodiazepine và chuyển ngay sang thuốc Bước 2 Levetiracetam / Fosphenytoin / Valproate.",
        "extra": "📖 Nguồn: AES 2016 Guidelines (Benzodiazepine Refractory Status)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Bay-qua-lieu-Benzo"],
    },
    {
        "id": "PED07-S63",
        "track": "ebm",
        "type": "basic",
        "category": "Bẫy quên test đường huyết",
        "section": "S8",
        "front": "Cạm bẫy lâm sàng số 3: Hậu quả nguy hiểm khi bỏ quên xét nghiệm đường huyết mao mạch ở trẻ đang co giật là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Hạ đường huyết nặng (&lt; 2,6 mmol/L) kích hoạt cơn co giật kháng thuốc chống động kinh quy ước.<br>2) Nếu tiêm nhiều thuốc chống co giật mà không bù đường: Cơn giật không dứt, bệnh nhân bị ngộ độc thuốc và nhu mô não bị hoại tử tế bào vĩnh viễn do thiếu glucose.<br>3) Bù ngay Glucose 10% liều 2 ml/kg tiêm TM sẽ cắt ngay cơn giật và cứu vãn hoàn toàn bộ não.<br><br><b>💡 Giải thích của AI:</b><br>Đường huyết mao mạch là 'bước kiểm tra sống còn' không bao giờ được phép quên trong tiếp cận ABCDE.",
        "extra": "📖 Nguồn: PALS & Pediatric Emergency Medicine Traps",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Bay-quen-duong-huyet"],
    },
    {
        "id": "PED07-S64",
        "track": "ebm",
        "type": "basic",
        "category": "Bẫy lạm dụng Paracetamol tĩnh mạch",
        "section": "S8",
        "front": "Cạm bẫy lâm sàng số 4: Sai lầm khi truyền tĩnh mạch Paracetamol (Perfalgan) trong lúc trẻ đang co giật là gì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Sai lầm nhận thức: Tưởng rằng hạ sốt sẽ cắt được cơn giật đang diễn ra.<br>2) Thực tế dược lý: Paracetamol cần 15–30 phút mới bắt đầu hạ nhiệt và hoàn toàn KHÔNG CÓ TÁC DỤNG CẮT CƠN CO GIẬT.<br>3) Nguy cơ: Làm mất thời gian vàng dùng thuốc chống co giật Bước 1 (Midazolam), đồng thời làm phân tán sự tập trung cấp cứu kiểm soát đường thở và oxy.<br><br><b>💡 Giải thích của AI:</b><br>Cắt cơn giật trước bằng Benzodiazepine, hạ sốt chỉ làm sau khi cơn co giật đã dứt hoàn toàn.",
        "extra": "📖 Nguồn: Pediatric Resuscitation Clinical Pearls",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Bay-Paracetamol-tinh-mach"],
    },
    {
        "id": "PED07-S65",
        "track": "ebm",
        "type": "basic",
        "category": "Bẫy kê đơn Phenobarbital phòng ngừa",
        "section": "S8",
        "front": "Cạm bẫy lâm sàng số 5: Vì sao việc kê đơn Phenobarbital hoặc Valproate uống hàng ngày để dự phòng sốt co giật đơn thuần là một sai lầm nghiêm trọng?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Phenobarbital gây tác dụng phụ độc thần kinh kéo dài: Làm giảm chỉ số thông minh (IQ), suy giảm trí nhớ, rối loạn hành vi và tăng động giảm chú ý ở trẻ nhỏ.<br>2) Valproate có nguy cơ gây độc tính hoại tử tế bào gan và viêm tụy.<br>3) Thuốc hoàn toàn không thay đổi được tiên lượng phát triển bệnh động kinh sau này.<br><br><b>💡 Giải thích của AI:</b><br>Đổi một cơn giật lành tính ngắn lấy sự suy giảm trí tuệ suốt đời của đứa trẻ là một can thiệp y khoa sai lầm đã bị AAP lên án và bãi bỏ.",
        "extra": "📖 Nguồn: AAP 2008 Guideline (Pediatrics 2008, PMID: 18310189)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Bay-Phenobarbital-du-phong"],
    },
    {
        "id": "PED07-S66",
        "track": "ebm",
        "type": "basic",
        "category": "Ca lâm sàng 1",
        "section": "S9",
        "front": "Case 1: Bé Nam 16 tháng (11 kg) sốt 39,2°C, xuất hiện co giật toàn thể hai bên trong 3 phút rồi tự hết. Khi đến viện sau 20 phút, trẻ tỉnh táo hoàn toàn, thóp phẳng, cổ mềm, họng đỏ có mủ. Phân loại và thái độ xử trí?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Phân loại: Co giật do sốt ĐƠN THUẦN (cơn toàn thể, &lt; 15 phút, 1 cơn duy nhất, không dấu thần kinh khu trú).<br>2) Thái độ xử trí chuẩn:<br>- KHÔNG chỉ định chọc dò dịch não tủy, KHÔNG làm EEG, KHÔNG chụp CT sọ não.<br>- Điều trị ổ nhiễm trùng: Khám tai mũi họng, chẩn đoán Viêm họng mủ cấp và kê đơn kháng sinh phù hợp.<br>- Hạ sốt bằng Paracetamol (10–15 mg/kg) khi sốt cao để giúp trẻ dễ chịu.<br>- Tư vấn trấn an gia đình về tính chất lành tính của bệnh và hướng dẫn checklist 5 nên - 5 không tại nhà.<br><br><b>💡 Giải thích của AI:</b><br>Trẻ tỉnh táo, có ổ nhiễm trùng rõ ràng ngoài thần kinh và tiêm chủng đủ ➜ Tránh mọi xét nghiệm xâm lấn không cần thiết.",
        "extra": "📖 Nguồn: Pediatric Clinical Case Studies (Case 1 Simple FS)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Case-1-don-thuan"],
    },
    {
        "id": "PED07-S67",
        "track": "ebm",
        "type": "basic",
        "category": "Ca lâm sàng 2",
        "section": "S9",
        "front": "Case 2: Bé Hoa 2 tuổi (12 kg) được mẹ bế vào phòng cấp cứu trong tình trạng đang co giật toàn thể liên tục phút thứ 8, tím môi, chưa có ven. Các bước xử trí cấp cứu tức thì?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Bước 1 (Ổn định đường thở): Đặt trẻ nằm nghiêng, hút sạch đờm dãi, thở oxy qua mask có túi dự trữ 10 L/phút.<br>2) Bước 2 (Cắt cơn giật ngay - không chờ chọc ven): Tiêm bắp sâu Midazolam liều 0,2 mg/kg = 2,4 mg (lấy 0,48 ml dung dịch 5mg/ml) tiêm vào mặt trước ngoài đùi.<br>3) Bước 3: Bấm đường huyết mao mạch ngay lập tức.<br>4) Bước 4: Điều dưỡng tiến hành đặt đường truyền tĩnh mạch và chuẩn bị liều Midazolam thứ 2 nếu sau 5 phút trẻ chưa dứt giật.<br><br><b>💡 Giải thích của AI:</b><br>Xử trí quyết đoán tiêm bắp Midazolam ngay phút thứ 8 giúp trẻ dứt cơn nhanh chóng trước mốc 15 phút, ngăn chặn nguy cơ tiến triển thành FSE.",
        "extra": "📖 Nguồn: Pediatric Emergency Medicine Case Studies (Case 2 Ongoing Seizure)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Case-2-dang-giat-chua-ven"],
    },
    {
        "id": "PED07-S68",
        "track": "ebm",
        "type": "basic",
        "category": "Ca lâm sàng 3",
        "section": "S9",
        "front": "Case 3: Bé Quân 14 tháng (10 kg) sốt 39,5°C co giật liên tục 22 phút, đã được tiêm 2 liều Midazolam (tổng 0,3 mg/kg) cách nhau 5 phút nhưng mắt vẫn trợn ngược và tay chân co giật từng cơn. Chẩn đoán và y lệnh Bước 2?",
        "back": "<b>🎯 Trả lời cốt lõi:</b><br>1) Chẩn đoán: Trạng thái động kinh do sốt kháng Benzodiazepine (Benzodiazepine-refractory Status Epilepticus).<br>2) Y lệnh xử trí Bước 2 tối khẩn:<br>- Tuyệt đối KHÔNG TIÊM thêm Benzodiazepine.<br>- Chỉ định: Levetiracetam (Keppra) liều 60 mg/kg = 600 mg pha trong 20 ml NaCl 0,9% truyền tĩnh mạch trong vòng 10 phút.<br>- Chuẩn bị sẵn bóng mask bóp bóng và dụng cụ đặt nội khí quản đề phòng suy hô hấp.<br>- Báo động kíp PICU hỗ trợ nếu cơn giật vượt qua mốc 30 phút.<br><br><b>💡 Giải thích của AI:</b><br>Levetiracetam là lựa chọn tối ưu lúc này vì kiểm soát cơn giật hiệu quả mà không làm suy sụp thêm hô hấp và huyết động sau 2 liều Midazolam.",
        "extra": "📖 Nguồn: Pediatric Neurocritical Care Case Studies (Case 3 Refractory SE)",
        "tags": ["PED-07", "EBM", "Chi-tiet", "Case-3-khang-Benzo"],
    }
]
